// Generated by scripts/generate-site-images.py; keep original PNGs as the source.
export const projectImages = {
  "proto-rs": {
    "src": "/assets/optimized/proto-rs-1495.450861656f7d.webp",
    "width": 1495,
    "height": 1002,
    "srcSet": "/assets/optimized/proto-rs-1495.450861656f7d.webp 1495w"
  },
  "wirebyte": {
    "src": "/assets/optimized/wirebyte-1028.db8c000604d1.webp",
    "width": 1028,
    "height": 666,
    "srcSet": "/assets/optimized/wirebyte-1028.db8c000604d1.webp 1028w"
  },
  "zenos": {
    "src": "/assets/optimized/zenos-1972.2964d4baa300.webp",
    "width": 1972,
    "height": 1196,
    "srcSet": "/assets/optimized/zenos-640.51ea050ccc28.webp 640w, /assets/optimized/zenos-1972.2964d4baa300.webp 1972w"
  },
  "lamp": {
    "src": "/assets/optimized/lamp-1271.0bbf2fba42bb.webp",
    "width": 1271,
    "height": 1002,
    "srcSet": "/assets/optimized/lamp-1271.0bbf2fba42bb.webp 1271w"
  },
  "sudoku-solver": {
    "src": "/assets/optimized/sudoku-solver-1200.31dac405068c.webp",
    "width": 1200,
    "height": 872,
    "srcSet": "/assets/optimized/sudoku-solver-1200.31dac405068c.webp 1200w"
  },
  "chinar": {
    "src": "/assets/optimized/chinar-1475.e52415c25e06.webp",
    "width": 1475,
    "height": 1002,
    "srcSet": "/assets/optimized/chinar-1475.e52415c25e06.webp 1475w"
  }
};

export const articleImages = {
  "/assets/gsoc.png": {
    "src": "/assets/optimized/gsoc-768.a020dfd5f5d9.webp",
    "width": 768,
    "height": 768,
    "srcSet": "/assets/optimized/gsoc-250.c12a8d2efdc2.webp 250w, /assets/optimized/gsoc-768.a020dfd5f5d9.webp 768w",
    "alt": "Google Summer of Code logo"
  },
  "/assets/vlc.png": {
    "src": "/assets/optimized/vlc-500.3c795d6e70c6.webp",
    "width": 500,
    "height": 500,
    "srcSet": "/assets/optimized/vlc-250.ffa22a7b26e5.webp 250w, /assets/optimized/vlc-500.3c795d6e70c6.webp 500w",
    "alt": "VLC media player traffic cone logo"
  }
};
