import { getAllBlogs } from '@/utils/mdx';
import Link from 'next/link';
import projects from '@/constants/projects';
import { SEO, Eyebrow, Arrow } from '@/components/ui';
export default function Project({ project }) {
  const nextProject =
    projects[(projects.findIndex((item) => item.slug === project.slug) + 1) % projects.length];
  return (
    <div className="shell project-detail">
      <SEO
        title={`${project.name}: Vikram Kangotra`}
        description={project.description}
        path={`/projects/${project.slug}`}
      />
      <Link className="back-link" href="/projects">
        ← All projects
      </Link>
      <div className="project-detail-header">
        <div>
          <Eyebrow>{project.label}</Eyebrow>
          <h1>{project.name}</h1>
          <p>{project.description}</p>
          <div className="tags">
            {project.tags.map((tag) => (
              <span key={tag}>{tag}</span>
            ))}
          </div>
        </div>
        <a
          className="button button-primary"
          href={project.href}
          target="_blank"
          rel="noopener noreferrer"
        >
          View source <Arrow diagonal />
        </a>
      </div>
      <div className="project-screenshot">
        {/* Static export serves the responsive assets generated by generate-site-images.py. */}
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={project.imageSrc.src}
          srcSet={project.imageSrcSet}
          width={project.imageSrc.width}
          height={project.imageSrc.height}
          alt={`${project.name} project preview`}
          sizes="(max-width: 800px) 90vw, 1100px"
          loading="eager"
          decoding="async"
        />
      </div>
      <div className="project-overview">
        <Eyebrow>ABOUT THE PROJECT</Eyebrow>
        <p>{project.detail}</p>
      </div>
      <nav className="project-next" aria-label="More projects">
        <Link className="text-link" href="/projects">
          All projects <Arrow />
        </Link>
        <Link className="text-link" href={`/projects/${nextProject.slug}`}>
          Next project: {nextProject.name} <Arrow />
        </Link>
      </nav>
    </div>
  );
}
export function getStaticPaths() {
  return {
    paths: projects.map((project) => ({ params: { slug: project.slug } })),
    fallback: false,
  };
}
export async function getStaticProps({ params }) {
  const project = projects.find((p) => p.slug === params.slug);
  return project ? { props: { project, blogs: await getAllBlogs() } } : { notFound: true };
}
