// This chapter exposes the output routines used by the earlier assembly labs.
// Inline aids use the existing interactive lesson renderer and stay serializable.
import { outputMechanicsSections } from './assemblyOutputMechanics';
const asm = (filename, source) => ({ language: 'asm', filename, source });
const fact = (label, value) => ({ label, value });
const node = (id, title, subtitle, explanation, facts = []) => ({ id, title, subtitle, explanation, facts });
const aid = (kind, title, intro, nodes, caption, connections) => ({
  kind, title, intro, nodes, caption, ...(connections ? { connections } : {}),
});
const teaching = (goal, bridge, prompt, answer, takeaway) => ({
  goal, bridge, check: { prompt, answer }, takeaway, diagramAfter: 2,
});
const putcSource = [
  'putc:',
  '    pushfd',
  '    pushad',
  '    push ds',
  '    push es',
  '    cld',
  '    mov ah, 0x0e',
  '    mov bx, 0x0007',
  '    int 0x10',
  '    pop es',
  '    pop ds',
  '    popad',
  '    popfd',
  '    ret',
].join('\n');
const newlineSource = [
  'newline:',
  '    pushfd',
  '    pushad',
  '    mov al, 13',
  '    call putc',
  '    mov al, 10',
  '    call putc',
  '    popad',
  '    popfd',
  '    ret',
].join('\n');
const putsSource = [
  'puts:',
  '    pushfd',
  '    pushad',
  '    cld',
  '.next:',
  '    lodsb',
  '    test al, al',
  '    jz .done',
  '    call putc',
  '    jmp .next',
  '.done:',
  '    popad',
  '    popfd',
  '    ret',
].join('\n');
const hexSource = [
  'print_hex16:',
  '    pushfd',
  '    pushad',
  '    mov dx, ax',
  '    mov cx, 4',
  '.digit:',
  '    rol dx, 4',
  '    mov al, dl',
  '    and al, 0x0f',
  "    add al, '0'",
  "    cmp al, '9'",
  '    jbe .emit',
  '    add al, 7',
  '.emit:',
  '    call putc',
  '    loop .digit',
  '    popad',
  '    popfd',
  '    ret',
].join('\n');

const outputChapters = [{
  id: 'A13',
  slug: 'assembly-output',
  title: 'Build the printing helpers you have been using',
  subtitle: 'Turn a BIOS character service into preserving character, line, string, and hexadecimal routines.',
  phase: 'x86 Assembly',
  minutes: 160,
  prerequisites: [
    'Use registers, byte loads, branches, loops, and local labels',
    'Balance near calls and mixed-width stack operations',
    'Read FLAGS and distinguish real-mode addresses from instruction encodings',
  ],
  outcomes: [
    'Implement putc, newline, puts, and print_hex16 as callable assembly routines',
    'Map PUSHAD, POPAD, PUSHFD, and POPFD to their saved bytes and restored processor state',
    'Preserve full general registers, caller flags, DS, and ES across output',
    'Trace the ordinary call frame and the nested BIOS interrupt frame',
    'Handle empty strings, incoming DF, leading zeroes, and every hexadecimal digit',
    'Separate the formatting algorithm from its firmware output dependency',
  ],
  sections: [
    {
      id: 'helper-boundary',
      title: 'Follow one helper call all the way to the screen',
      paragraphs: [
        "You have used CALL putc to observe a character and CALL print_hex16 to inspect a word. Each name marks ordinary instructions in the same loaded program as your lesson. A near CALL saves the next instruction address on the stack, changes IP to the helper, and eventually receives control back through RET. There is no printing instruction hidden behind these names. We can inspect the entire implementation and build it ourselves.",
        "Our smallest output operation uses a firmware service. putc accepts one byte in AL and requests BIOS teletype output. newline makes two character requests. puts visits the characters in a zero-terminated buffer. print_hex16 converts four nibbles into four character codes. The last three routines share putc, so only one place needs to know the firmware interface.",
        "The helper contract has two results: a deliberate output effect and a restored caller state. A debugging print should leave a pending comparison, a loop counter, and the upper half of a wide register available to the caller. We will make these promises explicit before writing each routine. Correct characters are one part of the executable checkpoints; the declared preservation and return checks are another.",
        "The workspace still supplies the disk loader, real-mode setup, stack, text video mode, and final halt. Write your helpers in console.asm under their actual names. lesson.asm is your editable caller for Run, and data.inc can hold strings. The usual built-in printing helpers are absent in this chapter. Submit calls the requested helper directly, so printing a fixed answer from lesson.asm cannot satisfy the checkpoint. The next chapter transfers the remaining boot responsibilities into your own files.",
      ],
      teaching: teaching(
        'Identify the instructions and interfaces behind each output helper.',
        'You can already debug a direct BIOS call. Now we will package that call so other code can safely reuse it.',
        'Which of the four helpers needs to know the BIOS teletype service number?',
        'putc needs it. The other helpers can express their output as calls to putc and depend on its preservation contract.',
        'A small output interface lets several independent algorithms share one device-facing implementation.',
      ),
      aid: aid('flow', 'Four interfaces, one firmware boundary',
        'Select a caller to inspect the representation it accepts and the requests it makes.',
        [
          node('string', 'puts', 'DS:SI → character sequence', 'Read successive bytes until zero and send each preceding byte to putc.', [fact('Example', '"Hi", 0 → H, i')]),
          node('word', 'print_hex16', 'AX → four hexadecimal characters', 'Extract four nibbles from most significant to least significant and encode each nibble.', [fact('Example', 'AX=0x002A → 0, 0, 2, A')]),
          node('line', 'newline', 'No argument → CR followed by LF', 'Choose two control bytes that establish the beginning of the following display row.', [fact('Bytes', '0x0D, 0x0A')]),
          node('character', 'putc', 'AL → one firmware request', 'Save caller state, select teletype output, invoke INT 0x10, restore state, and return.'),
          node('firmware', 'Video BIOS', 'INT 0x10 / AH=0x0E', 'Interpret the character, update the current text cursor or character cell, and return through the interrupt frame.'),
        ],
        'The arrows are calls and service requests. The caller resumes after each completed request.',
        [{ from: 'string', to: 'character', label: 'each nonzero byte' }, { from: 'word', to: 'character', label: 'four encoded digits' }, { from: 'line', to: 'character', label: 'two control bytes' }, { from: 'character', to: 'firmware', label: 'INT 0x10' }]),
    },
    {
      id: 'bios-teletype',
      title: 'Prepare a precise BIOS teletype request',
      paragraphs: [
        "INT 0x10 identifies the real-mode video interrupt interface. AH chooses a service within that interface. Set AH to 0x0E for teletype output and leave the character code in AL. Loading AH preserves AL because the two names select different bytes of AX. Loading AX with a new word would replace both the service and the character.",
        "The course starts in text mode 3 with display page zero active. Our wrapper sets BX to 0x0007: BH becomes zero and BL becomes seven. BH is conventionally the page argument; firmware implementations differ in how this teletype service uses it. SeaVGABIOS uses the active page. Selecting page zero during setup keeps these expectations aligned. BL supplies a foreground color in relevant graphics modes; this text-mode helper does not offer a general text-color parameter.",
        "A printable byte causes a character effect and advances the firmware cursor. Some byte values are control requests: carriage return and line feed alter the cursor, and backspace has its own behavior. Therefore the low-level interface accepts a byte, while the display decides how that byte behaves. We will build newline around the exact control bytes used by this environment.",
        "A software INT executes even when IF is clear. IF controls maskable hardware interrupt delivery. The real-mode interrupt operation temporarily saves return state and transfers to firmware through its vector. Returning from firmware restores the interrupt return state. Our own helper still needs to restore the general registers and any flags it changes while preparing the request.",
      ],
      teaching: teaching(
        'Construct the firmware request without losing the caller-supplied character.',
        'The call graph ends at putc. We now need the register interface used inside that routine.',
        "AL holds 0x5A. What happens to the intended character if the helper executes MOV AX, 0x0E00?",
        'AL becomes zero, so the request loses Z. MOV AH, 0x0E changes the service byte while preserving the character in AL.',
        'The service selector and its argument occupy separate byte fields that must both be correct at INT.',
      ),
      code: asm('teletype-request.asm', [
        "; Fragment inside a routine that has already saved caller state.",
        "; AL already holds the byte to emit.",
        'cld',
        'mov ah, 0x0e',
        'mov bx, 0x0007',
        'int 0x10',
      ].join('\n')),
      aid: aid('bits', 'The registers at the firmware boundary',
        'These are request fields at INT 0x10. The caller can have different values before entering putc.',
        [
          node('ah', 'AH = 0x0E', 'AX bits 15..8', 'Select teletype output. This write must preserve the lower byte containing the character.'),
          node('al', 'AL = character', 'AX bits 7..0', 'The caller supplies this byte. For Z, it is 0x5A.', [fact('Combined AX for Z', '0x0E5A')]),
          node('bh', 'BH = 0', 'BX bits 15..8', 'Use the page-zero convention, with page zero already active in the course environment.'),
          node('bl', 'BL = 7', 'BX bits 7..0', 'Provide a conventional foreground-color argument for firmware modes that use it. The exercise runs in text mode.'),
        ],
        'Save the original AX and BX before preparing these request fields. Restore the full EAX and EBX when the helper promises wide-register preservation.'),
    },
    {
      id: 'preservation-contract',
      title: 'Decide exactly what the caller gets back',
      paragraphs: [
        "Imagine a caller executes CMP AX, BX, prints a diagnostic, then uses JE. The branch still needs the comparison's ZF. A helper that prints the right character but returns flags from its own TEST or CMP has changed the caller's decision. The same problem arises when a string loop borrows SI or a number formatter borrows CX. We promise to restore the general registers and the ordinary flags used by these lessons.",
        "The CPU is at least a 386 even though the code runs in 16-bit real mode. Earlier lessons used EAX and other wide registers. PUSHAD saves eight dwords of general-register state; POPAD restores the general registers while skipping its saved stack-pointer slot. NASM emits the necessary operand-size override under BITS 16. PUSHA and POPA save only words, so they cannot protect the upper halves of registers when an implementation uses wider temporaries.",
        "PUSHFD must come before CLD, TEST, arithmetic, or any other instruction whose flags are private to the helper. POPFD belongs after the computation and register restoration. The lab's meaningful flag obligations include arithmetic flags and DF, with IF kept consistent with the caller's environment. Architectural control bits such as RF and VM have special PUSHFD/POPFD behavior; a promise about these printing helpers does not establish an arbitrary bit-for-bit EFLAGS serialization mechanism.",
        "PUSHAD does not save segment registers. putc crosses a firmware boundary, so it explicitly saves DS and ES as well. A string caller needs DS to continue addressing its own buffer after a character has been emitted. Startup establishes DS=0, but a checkpoint's sample setup can replace DS and ES before calling your code; preserve the values actually received. SS remains the established stack segment throughout these helpers. Every path must leave SP at its incoming value immediately before RET, so the original return offset is still on top.",
      ],
      teaching: teaching(
        'State and implement a preservation contract that includes wide registers, flags, and segments.',
        'A firmware request needs scratch registers. The helper must protect the values that belong to its caller.',
        'Why does saving AX fail to protect a caller whose EAX is 0xCAFE1234 if the helper later clears EAX?',
        'PUSH AX stores only 0x1234. POP AX restores those low bits, but the upper 0xCAFE remains lost. Save and restore the full register width promised by the interface.',
        'Preservation must cover each promised bit and each path back to the caller.',
      ),
      aid: aid('compare', 'Three independently observable obligations',
        'Use different observations for output, caller state, and return behavior.',
        [
          node('output', 'Requested output', 'Character or byte sequence', 'Check the character request and the resulting VGA behavior. A fixed literal can match one case while ignoring another input.'),
          node('state', 'Caller-owned state', 'Registers, flags, DS, ES', 'Use distinct high and low register halves and deliberate flag values. A helper that restores only a sample constant will fail other callers.'),
          node('return', 'Continuation', 'Balanced SS:SP and RET', 'The caller must resume at the instruction after CALL. Correct output followed by a jump into a saved register value violates the interface.'),
        ],
        'The executable contract names the observations it checks. Optional experiments can probe additional firmware behavior.'),
    },
    {
      id: 'putc-stack',
      title: 'Walk the two return frames inside putc',
      paragraphs: [
        "Take a caller whose SP is 0x7BFE just before CALL putc. This 16-bit near call reserves two bytes for its return offset, so putc begins at SP=0x7BFC. PUSHFD reserves four more bytes. PUSHAD reserves thirty-two. PUSH DS and PUSH ES reserve two bytes each under BITS 16. The wrapper reaches SP=0x7BD4 before entering firmware.",
        "INT 0x10 creates another return frame. In this ordinary real-mode case, the CPU saves a word of FLAGS, a word of CS, and a word of IP, bringing SP to 0x7BCE before any additional firmware stack use. Firmware finishes with its interrupt-return mechanism, which consumes its own frame and resumes our wrapper after INT. The helper's earlier near-call return offset is still waiting farther up the stack.",
        "Unwind our own saves in reverse order: ES, DS, the general registers, then flags. SP is again 0x7BFC. RET consumes the near return offset and resumes the caller with SP=0x7BFE. POPAD's skipped ESP slot is part of this accounting; replacing POPAD with a collection of pops requires implementing that special slot behavior deliberately.",
        "This trace gives the bytes reserved by the visible wrapper and the architectural interrupt frame. Firmware can use additional stack below them. Nested calls need additional room as well. A balanced routine can still exhaust an undersized stack, so stack balance and stack capacity are separate questions when you later choose your own bootloader's memory layout.",
      ],
      teaching: teaching(
        'Account for the helper call, saved state, and nested BIOS return frame.',
        'We have chosen the values to preserve. Now place each saved value at a concrete stack address.',
        'After firmware has returned and ES, DS, and the general registers have been restored, which saved object must POPFD consume?',
        'The original four-byte flag image saved by PUSHFD. Once POPFD releases it, the near return offset from CALL putc is the next stack object.',
        'Each boundary owns its own return frame; unwind the boundary you are currently leaving.',
      ),
      aid: aid('memory', 'Stack positions during one character request',
        'Addresses refer to SP after each operation, starting from caller SP=0x7BFE. Lower addresses appear later in this construction.',
        [
          node('call', '0x7BFC: return offset', 'CALL putc: 2 bytes', 'This continuation belongs to the caller and must survive all helper and firmware work.'),
          node('flags', '0x7BF8: saved flags', 'PUSHFD: 4 bytes', 'Capture flags before any helper instruction changes them.'),
          node('general', '0x7BD8: general-register block', 'PUSHAD: 32 bytes', 'Includes the original ESP value before PUSHAD. POPAD advances across that slot without restoring ESP from it.'),
          node('segments', '0x7BD4: ES and DS', 'Two word pushes: 4 bytes', 'ES is on top because it was pushed last. Restore ES before DS.'),
          node('interrupt', '0x7BCE: firmware return frame', 'INT: 6 architectural bytes', 'The interrupt frame stores its own return IP, CS, and FLAGS. Firmware may reserve more space below it.'),
        ],
        'After the interrupt returns, our wrapper unwinds back through segments, general registers, and flags, then RET consumes the caller continuation.'),
      deepDive: {
        title: 'Locate every saved value in the complete putc frame',
        paragraphs: [
          'The earlier PUSHAD diagram isolated the eight general-register slots. This trace places that block between the caller flag image and the segment saves. Each address below is physical because SS=0; ESP has a zero upper half in this example. The current top moves while older objects retain their addresses.',
          'There are also two different flag snapshots. PUSHFD captures the environment received by putc. The later INT captures the flags present at the firmware request, after the helper has executed CLD. If the caller arrived with DF=1, the saved caller image has DF=1 while the interrupt frame has DF=0. Firmware return restores its own entry flags; the final POPFD restores the outer caller’s flags.',
        ],
        example: {
          title: 'Build and release a mixed-width frame',
          intro: 'Start immediately before CALL putc with SP=0x7BFE. These addresses belong to this nested helper call; the lesson’s own return word is already at 0x7BFE.',
          steps: [
            { title: 'CALL saves the caller continuation', explanation: 'The two-byte near return offset is stored at 0x7BFC. putc must eventually leave that word at the top for RET.', state: 'SP=7BFC\n7BFC..7BFD  return IP after CALL putc\n7BFE..7BFF  older lesson return IP' },
            { title: 'PUSHFD saves the caller flags', explanation: 'Four bytes are reserved below the near return word. The flag snapshot must precede any helper instruction that changes a flag.', state: 'SP=7BF8\n7BF8..7BFB  caller EFLAGS image\n7BFC..7BFD  return IP' },
            { title: 'PUSHAD creates eight dword slots', explanation: 'The saved ESP value is 0x00007BF8, sampled before PUSHAD starts. The final top is 32 bytes lower. Reading upward from that top gives the order POPAD will traverse.', state: 'SP=7BD8\n7BD8..7BDB  EDI\n7BDC..7BDF  ESI\n7BE0..7BE3  EBP\n7BE4..7BE7  saved ESP = 00007BF8\n7BE8..7BEB  EBX\n7BEC..7BEF  EDX\n7BF0..7BF3  ECX\n7BF4..7BF7  EAX' },
            { title: 'Save the segment registers', explanation: 'Under BITS 16, PUSH DS and PUSH ES each reserve a word. ES becomes the newest item, so POP ES must occur before POP DS.', state: 'SP=7BD4\n7BD4..7BD5  ES\n7BD6..7BD7  DS\n7BD8..7BDB  saved EDI' },
            { title: 'INT creates the firmware continuation', explanation: 'The ordinary 16-bit real-mode interrupt entry adds FLAGS, CS, and IP as words. The topmost word is IP. Firmware may push additional values below this architectural frame and must release its own work before returning.', state: 'SP=7BCE before firmware-local saves\n7BCE..7BCF  firmware return IP\n7BD0..7BD1  firmware return CS\n7BD2..7BD3  flags at INT\n7BD4..7BD5  helper-saved ES' },
            { title: 'Restore each block in reverse order', explanation: 'After the firmware interrupt return, SP is 0x7BD4 again. POP ES and POP DS reach the general-register block. POPAD restores EDI, ESI and EBP, advances over the saved ESP slot, then restores EBX, EDX, ECX and EAX. Its total release is 32 bytes. POPFD then consumes the caller flag image.', state: 'Firmware return  SP=7BD4\nPOP ES           SP=7BD6\nPOP DS           SP=7BD8\nPOPAD            SP=7BF8\nPOPFD            SP=7BFC' },
            { title: 'RET consumes the helper continuation', explanation: 'The top now contains the original near return offset. RET loads it into IP and releases its two bytes. The caller resumes with the same SP it had immediately before CALL putc.', state: 'RET              SP=7BFE\nCaller registers, DS, ES and ordinary flags restored\nDisplayed character remains on screen' },
          ],
          conclusion: 'The visible helper saves use 40 bytes. Its near CALL adds two and the real-mode interrupt entry adds six, for 48 bytes below the pre-call pointer before firmware-local stack use.',
        },
        pitfalls: [
          { title: 'Restoring the register block while ES is still on top', text: 'POPAD consumes bytes starting at the current top. Leaving the segment saves there shifts every register read and eventually consumes bytes belonging to another object. Release ES and DS first.' },
          { title: 'Using POPF after PUSHFD', text: 'A word-sized POPF releases only two of the four saved flag bytes in this BITS 16 example. Two bytes remain ahead of the near return word, so the following RET takes its destination from the wrong location.' },
          { title: 'Replacing the skipped slot with POP ESP', text: 'POPAD advances past that dword. Loading its value into ESP would change the base for all remaining reads and break this restore sequence.' },
        ],
        transfer: 'Repeat the drawing with a caller SP of 0x7000. Subtract the same byte counts, mark the saved ESP value at the PUSHAD boundary, and verify that the final RET returns the pointer to 0x7000. Reserve additional space for the firmware’s own work.',
      },
    },
    {
      id: 'putc-checkpoint',
      title: 'Implement putc with a complete return contract',
      paragraphs: [
        "Create console.asm and define putc. AL already contains its input. Save flags and the full general registers before borrowing AH or BX, save DS and ES, clear DF for the firmware call, then construct the teletype request. After INT returns, restore every saved object in reverse order and execute a near RET. Keep your exploratory calls in lesson.asm.",
        "The worked implementation below is the same small design used by the earlier course helper. Its pushes read the registers without changing the character in AL. The request then temporarily gives AH, BH, and BL their firmware meanings. The restoration deliberately returns the caller's whole EAX and EBX, including the high halves, even though only byte-sized request fields were needed.",
        "Run several character inputs and compare the resulting output. Then Submit the implementation against the checkpoint's declared machine cases. Check the preserved state as carefully as the visible character. A version that reloads a convenient fixed AX value after printing may appear correct for one input but breaks the callable interface.",
        "Keep personal notes if they help your reasoning. The checkpoint is completed by executable behavior. The required file, labels, input values, and preservation checks are listed in its Problem brief. Follow that interface when placing the routine beside any driver code supplied by the workspace.",
      ],
      teaching: teaching(
        'Build a callable BIOS character helper that restores its caller.',
        'The stack trace has accounted for every save. We can now turn that trace into the complete routine.',
        'Why does the routine save flags before CLD even when most of your earlier callers began with DF=0?',
        'The helper must also handle a permitted caller with DF=1. It establishes DF=0 internally for forward-oriented work, then restores the original DF as part of the saved flags.',
        'A reusable helper preserves the caller it actually receives.',
      ),
      code: asm('console.asm', putcSource),
      callout: { title: 'Write the routine, then run the cases', text: 'Use the Problem brief for the exact file and callable label. The executable checks assess the input-dependent output, declared caller state, and safe return. No written response is required for a pass.' },
    },
    {
      id: 'newline-cursor',
      title: 'Build a line break from two cursor operations',
      paragraphs: [
        "A text cursor has a row and a column. Carriage return, byte 13 or 0x0D, moves the column to zero. Line feed, byte 10 or 0x0A, advances the row while retaining the column. Combining CR and LF gives our newline contract: begin the next row at its first column, subject to firmware scrolling at the bottom.",
        "Suppose the cursor is on row 2, column 7. CR produces row 2, column 0; LF then produces row 3, column 0. Sending only LF leaves the next character on row 3, column 7. Sending only CR makes the next character overwrite the beginning of row 2. These effects explain why a screen containing some correct letters can still have the wrong layout.",
        "newline has no caller argument. It creates two temporary AL values, 13 followed by 10, and passes each to putc. Although putc preserves its own caller's AL, that caller is newline. After the second call, AL is still the temporary value 10. newline must separately preserve the AL value that its outer caller supplied before newline began.",
        "The output contract is the ordered pair CR, LF. In uncomplicated cursor positions, LF followed by CR can arrive at the same final coordinates. Checking only the final cursor would therefore leave the byte ordering unobserved. An output trace can establish the sequence, while cursor and VGA observations establish its display consequences. Read the checkpoint's declared checks to see which evidence it collects.",
      ],
      teaching: teaching(
        'Derive newline from carriage return and line feed while preserving the outer caller.',
        'We can emit one byte safely. Two carefully chosen bytes can now express a line-level operation.',
        'From row 4, column 12, where does the cursor go after LF alone and after CR followed by LF?',
        'LF alone reaches row 5, column 12. CR followed by LF reaches row 5, column 0, assuming neither path reaches the bottom scroll boundary.',
        'A line break is a defined sequence of device operations with its own preservation contract.',
      ),
      aid: aid('trace', 'Trace CR and LF separately',
        'Start at row 2, column 7. The next printable character should land at row 3, column 0.',
        [
          node('start', 'Before newline', 'row=2, column=7', 'The current cursor includes both a horizontal and a vertical coordinate.'),
          node('cr', 'Emit 0x0D', 'row=2, column=0', 'Carriage return changes the horizontal coordinate. It consumes no printable cell.'),
          node('lf', 'Emit 0x0A', 'row=3, column=0', 'Line feed advances the vertical coordinate. At the bottom, firmware must scroll to preserve a visible cursor.'),
          node('next', 'Emit B', 'B occupies row 3, column 0', 'The next character is written at the new coordinates and the cursor advances to column 1.'),
        ],
        'The diagram assumes the cursor starts above the bottom row. Test scrolling separately when developing a larger console.'),
    },
    {
      id: 'newline-checkpoint',
      title: 'Implement newline by composing preserving calls',
      paragraphs: [
        "Keep putc in console.asm and add newline around two calls to that character interface. Save the outer caller's state, load AL with 13 and call putc, then load AL with 10 and call putc again. Restore the saved state and return. The example uses the same PUSHFD/PUSHAD pattern as the other helpers so the preservation policy remains easy to audit.",
        "newline relies on putc to preserve DS and ES across the firmware requests. It does not otherwise alter those segments. This is composition through a contract: you can derive the outer behavior from the guarantees of the operation it calls. If you later replace putc with a different implementation, the replacement must continue to satisfy those guarantees.",
        "Submit calls newline directly and checks the resulting cursor position, preserved general registers, flags and segments, and balanced stack return. The cases include the bottom row to exercise scrolling. They observe the resulting machine state; they do not trace the exact order of the two firmware requests. Use CR followed by LF to implement the stated interface, and use lesson.asm for your own visible callers during Run.",
      ],
      teaching: teaching(
        'Compose two putc calls without leaking newline’s temporary values.',
        'The cursor model tells us which bytes to send. The remaining task is preserving the state around those requests.',
        'putc preserves all general registers. Why would a newline implementation that only loads AL twice still need its own save and restore?',
        'newline itself overwrites AL before each call. putc preserves those temporary inputs, so newline must retain and restore the original outer-caller EAX separately.',
        'Every routine owns the changes it makes before invoking a preserving callee.',
      ),
      code: asm('console.asm', newlineSource),
      aid: aid('flow', 'Two nested callers, two preservation boundaries',
        'Each helper restores the state present at its own entry.',
        [
          node('outer', 'Caller → newline', 'Original EAX', 'The outer caller owns the original EAX and other preserved state. newline saves that state.'),
          node('cr', 'newline → putc', 'AL=13', 'putc receives 13, emits CR, and returns with AL still 13.'),
          node('lf', 'newline → putc', 'AL=10', 'putc receives 10, emits LF, and returns with AL still 10.'),
          node('restore', 'newline → caller', 'Original EAX restored', 'newline restores its own entry snapshot before returning to the outer caller.'),
        ],
        'Preservation is relative to the entry of each call. The temporary arguments belong to the routine that prepared them.'),
    },
    {
      id: 'string-addresses',
      title: 'Give a string both an address and an end rule',
      paragraphs: [
        "puts accepts a real-mode pointer in DS:SI. DS chooses a segment base and SI supplies the byte offset. For DS=0x1000 and SI=0x0230, the first byte is at physical address 0x10230. The checkpoint uses the course's DS=0 data layout, but naming both parts explains why changing SI alone is insufficient when code and data use different segments.",
        "A zero-terminated string stores its characters followed by byte zero. For the declaration message: db 'Hi', 0, the bytes are 0x48, 0x69, and 0x00. The label gives the first byte's address. MOV SI, message loads that address; MOV SI, [message] would instead load a word made from the first two stored bytes. Those are different inputs to the traversal.",
        "Our contract requires a readable terminator before the 16-bit offset would wrap. The helper does not receive a length or a memory-map description, so it cannot establish that an arbitrary pointer is safe. A missing zero could make it scan unrelated code or data. The later kernel's user-buffer interfaces will need explicit bounds and address validation.",
        "The empty string is a buffer whose very first byte is zero. It still has an address and a valid terminator, but no character request is needed. A zero byte inside a larger allocation ends the string even if other bytes follow it. puts must leave the entire supplied buffer unchanged because reading text grants no permission to rewrite it.",
      ],
      teaching: teaching(
        'Interpret DS:SI as a byte pointer and zero as the representation’s termination rule.',
        'Character output is callable. We can now use memory to supply a sequence of characters.',
        "Memory contains 41 00 42 00. How many bytes should puts emit when SI points at the first byte?",
        'It emits one byte, 0x41. The following zero ends that string. The later 0x42 belongs to storage beyond its terminator.',
        'The pointer locates the first byte; the string representation determines which following bytes belong to the value.',
      ),
      aid: aid('memory', 'A buffer, its terminator, and the next byte',
        'Assume DS=0x1000 and SI=0x0230. Each block below is one byte.',
        [
          node('h', '0x10230: 48', 'DS:0230 → H', 'This is the first readable character. SI names its offset, and DS supplies the segment base.'),
          node('i', '0x10231: 69', 'DS:0231 → i', 'The next byte belongs to the same string because no zero has been encountered.'),
          node('zero', '0x10232: 00', 'DS:0232 → stop', 'The terminator is read to make the stopping decision. It is never passed to putc.'),
          node('after', '0x10233: A5', 'Outside this string', 'The allocation can contain more bytes, but the traversal must already have ended. This byte must remain unchanged.'),
        ],
        'The temporary SI reaches 0x0233 after reading the terminator. The preserving helper restores the original caller SI before returning.'),
    },
    {
      id: 'string-loop',
      title: 'Establish the loop invariant before loading another byte',
      paragraphs: [
        "At the top of the loop, SI points to the next byte that has not yet been examined. All earlier nonzero bytes have been sent to putc exactly once. LODSB reads DS:SI into AL, then adjusts SI according to DF. CLD makes the adjustment advance by one, giving a forward traversal independent of the caller's incoming direction.",
        "Test AL immediately after the load. If it is zero, branch to the common restoration path. Otherwise call putc and return to the loop. The branch must precede the output call so that an empty string emits nothing. The helper's local .next and .done labels make the back edge and exit explicit.",
        "puts saves flags before clearing DF. A caller may have been preparing a backward copy with DF=1. During puts, the string still prints forward; after puts returns, the caller sees its original DF again. TEST changes several arithmetic flags during the loop, so restoring only DF with STD or CLD would leave the rest of the caller's flag state damaged.",
        "putc preserves the updated SI, the loop's registers, and DS. Consequently each iteration can trust the pointer it established before requesting output. Without that lower-level contract, a firmware call could send the next load to the wrong address. Reusing a helper is safe only when the properties needed by the loop are part of its interface.",
      ],
      teaching: teaching(
        'Maintain a forward, terminating string loop while preserving incoming flags.',
        'The representation tells us where the string ends. Now order the load, decision, and output so every boundary case follows that rule.',
        'A caller enters with DF=1 and SI at the H in "Hi". When must puts clear DF and when must it restore the original flags?',
        'Save the flags first, then execute CLD before the first LODSB. Restore the original flags at the common exit after the loop and register restoration.',
        'Save the caller’s environment, establish the environment your algorithm needs, and restore the caller’s environment on exit.',
      ),
      deepDive: {
        title: 'Read the empty path and the nonempty path from the same loop',
        paragraphs: [
          "A useful invariant survives every trip around a loop. Here the private SI moves forward, previously emitted bytes are exactly the prefix before SI, and the original caller state remains saved on the stack. Reaching zero ends the loop through the same restoration code regardless of string length.",
        ],
        example: {
          title: 'The three reads for "Hi"',
          intro: 'Let SI initially be 0x0230 and let the bytes at DS:SI be 48 69 00.',
          steps: [
            { title: 'Read H', explanation: 'LODSB reads 48 and advances private SI to 0x0231. TEST finds a nonzero byte, so putc emits H.', state: 'AL=48  SI=0231  output=H' },
            { title: 'Read i', explanation: 'The next load reads 69 and advances SI to 0x0232. The same nonzero path emits i.', state: 'AL=69  SI=0232  output=Hi' },
            { title: 'Read the terminator', explanation: 'The load reads zero and advances private SI to 0x0233. The zero branch goes directly to restoration.', state: 'AL=00  SI=0233  output=Hi' },
            { title: 'Restore and return', explanation: 'POPAD restores the original ESI, including SI=0x0230, and POPFD restores the caller flags. The caller then resumes.', state: 'Caller SI=0230  buffer unchanged' },
          ],
          conclusion: 'A string with n nonzero bytes performs n+1 reads and n character requests. The extra read establishes that the string ended.',
        },
        flowchart: {
          title: 'The puts control flow',
          intro: 'The zero branch reaches the same restoration block used after any number of emitted characters.',
          nodes: [
            { id: 'save', label: 'Save caller state; CLD', detail: 'Capture flags before changing DF, save the general registers, and establish forward traversal.' },
            { id: 'load', label: 'LODSB', detail: 'Read DS:SI into AL and advance private SI to the following byte.' },
            { id: 'zero', label: 'Is AL zero?', kind: 'decision', detail: 'Use TEST AL, AL. Zero ends the string before any output request for that byte.' },
            { id: 'emit', label: 'CALL putc', detail: 'Emit the current byte. The preserving character helper retains the private SI used by this loop.' },
            { id: 'restore', label: 'Restore state; RET', kind: 'terminal', detail: 'Restore the original registers and flags, then consume the ordinary near return offset.' },
          ],
          edges: [
            { from: 'save', to: 'load', label: 'begin' },
            { from: 'load', to: 'zero', label: 'inspect byte' },
            { from: 'zero', to: 'restore', label: 'yes' },
            { from: 'zero', to: 'emit', label: 'no' },
            { from: 'emit', to: 'load', label: 'next byte' },
          ],
          caption: 'The empty string takes the zero exit on its first iteration and still restores every saved object.',
        },
        pitfalls: [
          { title: 'Emitting before testing', text: 'The first zero would reach putc, so the empty input would perform an unwanted request.' },
          { title: 'Saving flags after CLD', text: 'The saved image would already contain DF=0 and could no longer restore a caller that arrived with DF=1.' },
          { title: 'Returning from inside the loop', text: 'A direct RET before the common restoration block would read saved state as a return offset.' },
        ],
        transfer: 'Try a buffer beginning with zero followed by printable bytes. The loop must perform zero character requests and leave those later bytes untouched.',
      },
    },
    {
      id: 'puts-checkpoint',
      title: 'Implement puts and exercise its boundary inputs',
      paragraphs: [
        "Add puts to console.asm while keeping putc and newline. Keep a message buffer with at least 64 bytes in data.inc, as the Problem brief requires for its varied strings. The routine receives DS:SI from its caller. Save the full general registers and flags, establish forward direction, and implement the load-test-emit loop. Leave all source bytes unchanged. Restore the original ESI and other caller state before returning.",
        "In lesson.asm, use a label in data.inc to try your own string and then call newline. A second useful Run uses an empty string. A third contains a zero followed by another recognizable byte so you can see whether traversal stops early enough. These exploratory callers help you locate mistakes; Submit supplies its own inputs and calls puts directly.",
        "The worked version below uses only the promised putc interface. It does not call an existing course puts. All printing helpers in this chapter come from your console.asm. If the string appears in reverse order, repeats, or reaches unrelated text, inspect DF, the SI initialization in the caller, and the position of the terminator check.",
        "Check preservation with an input ESI whose upper half is distinguishable from its low pointer offset. The 16-bit LODSB path advances SI, but the caller owns the entire ESI value. A general-register save and restore makes that width obligation explicit. The same tests can inspect a distinct ES value even though puts itself never needs ES to read its source.",
      ],
      teaching: teaching(
        'Write a preserving puts that handles empty and varied strings using their supplied bytes.',
        'The loop and its exit have been traced. Build that traversal into your growing console library.',
        'For a three-character string followed by zero, what must the caller see in SI after puts returns?',
        'The same SI value that the caller supplied. The helper advanced a private working copy while traversing, then restored the saved original.',
        'A traversal can consume data logically while leaving both the buffer and the caller’s pointer unchanged.',
      ),
      code: asm('console.asm', putsSource),
      aid: aid('compare', 'Choose inputs that expose different string defects',
        'Each case exercises a different part of the callable contract.',
        [
          node('empty', '00', 'Empty string', 'The first read immediately takes the restoration path. No output request should occur.'),
          node('one', '5A 00', 'One character', 'Exactly one character request occurs before the terminator. This makes off-by-one output easy to see.'),
          node('several', '41 42 43 00', 'Several characters', 'The helper must advance through every byte in order and preserve the source buffer.'),
          node('direction', 'Same bytes, DF=1 on entry', 'Caller environment differs', 'puts temporarily clears DF to obtain the same forward text, then restores the original DF before returning.'),
        ],
        'Pointer validity and a terminator before offset wrap are caller preconditions for this small interface.'),
    },
    {
      id: 'hexadecimal-fields',
      title: 'Separate the number, its nibbles, and its text',
      paragraphs: [
        "AX contains a sixteen-bit pattern. To display it in hexadecimal with a fixed width of four characters, split it into four nibbles: bits 15..12, 11..8, 7..4, and 3..0. A nibble is a value from zero through fifteen. The text encoder maps those values to the character codes for 0 through 9 and A through F.",
        "The value 0x002A contains nibbles 0, 0, 2, and 10, so the output is the four-character text 002A. Each displayed zero is intentional. This fixed width makes addresses and register dumps easy to align. A minimal-width formatter would need a different leading-zero policy and an explicit rule for the all-zero value.",
        "An ASCII digit begins at code 0x30. Adding '0' maps nibble values 0 through 9 to '0' through '9'. Applying the same addition to ten gives 0x3A, the code for a colon. The uppercase letter A is 0x41, seven codes farther on. Thus values above nine need an additional seven after adding '0'.",
        "Byte order in memory does not decide the order of hexadecimal digits on the screen. A stored little-endian word 0x002A has low byte 2A first and high byte 00 second. Our formatter reads the value in AX and deliberately emits its most significant nibble first. It also chooses no sign prefix: AX=0xFFFF prints FFFF whether the caller interprets that pattern as unsigned 65535 or signed minus one.",
      ],
      teaching: teaching(
        'Convert every nibble into an uppercase hexadecimal character while keeping a fixed four-character width.',
        'puts reads text that already exists. print_hex16 must construct the text from a binary value.',
        "What character code results from adding '0' to nibble 10, and how does the formatter turn it into A?",
        "The intermediate code is 0x3A. Adding seven produces 0x41, the ASCII code for uppercase A.",
        'Formatting is an explicit mapping from a stored pattern to an ordered sequence of character codes.',
      ),
      aid: aid('bits', 'AX=0xA03F becomes four printable characters',
        'Read from the most significant nibble toward the least significant.',
        [
          node('high', '1010 → A', 'bits 15..12', 'Nibble ten maps to character code 0x41.', [fact('ASCII calculation', '10 + 0x30 + 7 = 0x41')]),
          node('middle1', '0000 → 0', 'bits 11..8', 'A zero nibble still produces one printable digit under the fixed-width contract.', [fact('ASCII calculation', '0 + 0x30 = 0x30')]),
          node('middle2', '0011 → 3', 'bits 7..4', 'Nibble three is within the numeric digit range.', [fact('ASCII calculation', '3 + 0x30 = 0x33')]),
          node('low', '1111 → F', 'bits 3..0', 'Nibble fifteen maps to the last uppercase hexadecimal letter.', [fact('ASCII calculation', '15 + 0x30 + 7 = 0x46')]),
        ],
        'The output bytes are 41 30 33 46. The original AX pattern remains 0xA03F after the preserving helper returns.'),
    },
    {
      id: 'hexadecimal-loop',
      title: 'Move the next nibble into a convenient position',
      paragraphs: [
        "Copy AX into DX so the formatter can use AL for character codes without destroying the unprocessed input. Set CX to four. At the start of each iteration, rotate DX left by four bits. The nibble that was at the high end moves to the low end, where copying DL into AL and masking with 0x0F isolates it.",
        "For DX=0xA03F, the first rotation produces 0x03FA and exposes A. The next three rotations produce 0x3FA0, 0xFA03, and 0xA03F, exposing 0, 3, and F. Four rotations traverse all four nibbles and bring the scratch word back to its starting bit pattern. We still restore the original EDX from the stack because the caller may have supplied an unrelated value in that register.",
        "After masking, add '0', compare the resulting character code with '9', and use an unsigned condition to decide whether to add seven. The range is tightly bounded: AL is now between 0x30 and 0x3F. This bound makes the comparison easy to justify. putc preserves the remaining scratch value in DX and the loop count in CX across each character request.",
        "LOOP decrements CX and returns to the digit step while the count remains nonzero. We deliberately enter with four, so exactly four characters are emitted. Rotation, masking, addition, and comparison all create flags private to this implementation; restore the caller's original flags after the last iteration. Never branch in the caller based on the formatter's final comparison by accident.",
      ],
      teaching: teaching(
        'Trace a four-iteration formatter whose scratch state survives its output calls.',
        'We can encode one nibble. Now choose each nibble in the order required by the output format.',
        'Why does the implementation copy AX into DX before writing an ASCII digit into AL?',
        'AL is part of the original AX input. Keeping the unprocessed pattern in DX allows AL to hold each outgoing character without losing the remaining input nibbles.',
        'Keep the source representation in one place and construct each output unit in a separate temporary.',
      ),
      deepDive: {
        title: 'A loop invariant for hexadecimal output',
        paragraphs: [
          "After k completed iterations, exactly the first k high-to-low nibbles of the original word have been emitted. CX is 4-k and DX has been rotated left by 4k bits. These three facts connect the visible prefix, the remaining work, and the private representation.",
        ],
        example: {
          title: 'Trace all four digits of 0xA03F',
          intro: 'Each row gives DX after rotation, the isolated nibble, and the completed output prefix.',
          steps: [
            { title: 'Iteration 1', explanation: 'Rotate A03F to 03FA. Isolate A, map it to character 41, and emit A.', state: 'DX=03FA  nibble=A  output=A     CX after LOOP=3' },
            { title: 'Iteration 2', explanation: 'Rotate 03FA to 3FA0. The low nibble is zero, which maps to character 30.', state: 'DX=3FA0  nibble=0  output=A0    CX after LOOP=2' },
            { title: 'Iteration 3', explanation: 'Rotate 3FA0 to FA03. The low nibble three maps to character 33.', state: 'DX=FA03  nibble=3  output=A03   CX after LOOP=1' },
            { title: 'Iteration 4', explanation: 'Rotate FA03 to A03F. Fifteen maps to character 46. LOOP reaches zero and exits.', state: 'DX=A03F  nibble=F  output=A03F  CX after LOOP=0' },
          ],
          conclusion: 'Four iterations determine the width. The digit conversion determines the alphabet. Register restoration determines what the caller receives afterward.',
        },
        flowchart: {
          title: 'The fixed-width hexadecimal formatter',
          intro: 'The digit conversion has two paths, both of which rejoin before output.',
          nodes: [
            { id: 'save', label: 'Save state; DX=AX; CX=4', detail: 'Keep the original caller values on the stack and establish the private source and count.' },
            { id: 'nibble', label: 'Rotate; isolate nibble; add 0x30', detail: 'ROL DX,4 exposes the next nibble. MOV AL,DL and AND AL,0x0F isolate it. Adding the code for zero begins the mapping.' },
            { id: 'digit', label: 'Is AL at most 0x39?', kind: 'decision', detail: 'CMP AL,0x39 and an unsigned conditional branch distinguish the digit codes from the letter range.' },
            { id: 'letter', label: 'Add seven', detail: 'Values corresponding to nibbles ten through fifteen move from 3A..3F to uppercase A..F at 41..46.' },
            { id: 'emit', label: 'CALL putc', detail: 'Emit the converted character while preserving DX and CX for the next iteration.' },
            { id: 'count', label: 'Decrement CX; any digits left?', kind: 'decision', detail: 'LOOP both decrements the count and follows the back edge when another nibble remains.' },
            { id: 'restore', label: 'Restore state; RET', kind: 'terminal', detail: 'Restore the original EAX, EDX, ECX, other general registers, and flags before returning.' },
          ],
          edges: [
            { from: 'save', to: 'nibble', label: 'begin' },
            { from: 'nibble', to: 'digit', label: 'classify' },
            { from: 'digit', to: 'emit', label: 'yes: 0..9' },
            { from: 'digit', to: 'letter', label: 'no: A..F' },
            { from: 'letter', to: 'emit', label: 'converted' },
            { from: 'emit', to: 'count', label: 'one digit done' },
            { from: 'count', to: 'nibble', label: 'yes' },
            { from: 'count', to: 'restore', label: 'no' },
          ],
          caption: 'A different implementation can use shifts or a lookup table while satisfying the same externally observed contract.',
        },
        pitfalls: [
          { title: 'Formatting through AX alone', text: 'Writing a character into AL can overwrite input bits that later iterations still need.' },
          { title: 'Assuming the output call preserves CX', text: 'The loop requires that guarantee. Our putc explicitly supplies it; a bare firmware call would need separate preservation reasoning.' },
          { title: 'Dropping leading zeroes', text: 'That implements a different format. This helper must emit exactly four uppercase digits for every AX input.' },
        ],
        transfer: 'Trace 0x000A, 0x9000, and 0xFFFF. Together they exercise leading zeroes, the 9-to-A conversion boundary, digit position, and repeated letters.',
      },
    },
    {
      id: 'hex-checkpoint',
      title: 'Implement print_hex16 for every sixteen-bit pattern',
      paragraphs: [
        "Add print_hex16 to console.asm while retaining the other three helpers. The input is the current AX, and the result is exactly four uppercase hexadecimal characters. Emit no prefix, spaces, sign, or automatic newline. This narrow format lets callers choose their own surrounding labels and line layout.",
        "The worked implementation uses rotation and arithmetic conversion, but the executable contract permits another correct algorithm. A sixteen-byte lookup table is also possible if its addressing and segment assumptions are valid. Whatever method you choose, compute the output from the supplied input and preserve the full caller state.",
        "Use Run to inspect words with different structures: 0x0000, 0x0009, 0x000A, 0xA03F, and 0xFFFF. The expected strings are 0000, 0009, 000A, A03F, and FFFF. These values expose leading-zero removal, the digit-to-letter boundary, reversed nibble order, and all-letter output. Submit calls print_hex16 directly with the checkpoint's varied inputs and preservation sentinels.",
        "A caller may supply EAX=0xCAFE002A. AX is the formatting argument, so the visible text is 002A; the full EAX value must return unchanged. Similarly, the caller's ECX and EDX can contain unrelated live values even though the implementation needs private copies in CX and DX. The save/restore boundary gives the formatter temporary working space without taking ownership of those caller values.",
      ],
      teaching: teaching(
        'Implement and test a general four-digit hexadecimal formatter.',
        'The digit mapping and loop now have separate explanations. Combine them behind the callable interface.',
        'What should print_hex16 display for EAX=0xCAFE002A, and what should EAX contain afterward?',
        'It should display 002A because AX is the argument. EAX must still be 0xCAFE002A after the helper returns.',
        'The input width controls the format; the preservation contract controls the state restored to the caller.',
      ),
      code: asm('console.asm', hexSource),
      callout: { title: 'Keep formatting policy explicit', text: 'This function prints four uppercase hexadecimal digits and returns. Call newline separately when you want a line break. Submit checks the behavior of your implementation with varied inputs.' },
    },
    {
      id: 'composing-the-library',
      title: 'Assemble a diagnostic line from small contracts',
      paragraphs: [
        "A useful diagnostic can now be assembled from ordinary calls: print a label with puts, print a register word with print_hex16, then call newline. The label is already encoded text, the word still needs formatting, and the line ending expresses cursor policy. Keeping these responsibilities separate makes the caller short enough to read as an intended output sequence.",
        "In the example, data.inc contains a zero-terminated label, and lesson.asm establishes DS=0 before supplying its address in SI. This setup matters because the selected checkpoint can seed DS with a preservation sentinel. puts restores the supplied SI, but setting SI in the caller was still a change made by the caller. If a larger caller needs its previous ESI value later, that caller must save it before assigning the label pointer. The same reasoning applies when it loads AX with the value to print.",
        "Nested calls increase the maximum temporary stack usage even though each one balances its own frame. A CALL puts frame leads to its saved flags and general registers, then a CALL putc frame, putc's saves, and the BIOS interrupt frame. None of those inner saves can overlap a live outer save. Reserve enough stack for the deepest active path plus firmware's own stack use.",
        "The final library contains ordinary labels in console.asm. The chapter's runtime supplies a separate entry that invokes lesson.asm for Run, while Submit chooses a helper entry and its test inputs. Keeping the exploratory caller separate prevents fixed output in the caller from hiding an incomplete helper. All four helpers remain available for your own combinations once you have written them.",
      ],
      teaching: teaching(
        'Compose a readable diagnostic caller and account for nested preservation boundaries.',
        'All four interfaces are implemented. We can now use their guarantees to reason about a short program.',
        'If puts preserves ESI, does that undo a MOV SI,label performed by its caller immediately before CALL?',
        'No. That MOV established the state at puts entry. puts restores that state. The caller must save any older ESI value it wants to recover.',
        'A preserving callee restores its entry state; callers remain responsible for their own setup changes.',
      ),
      code: asm('lesson.asm', [
        '; lesson.asm',
        '; Establish the segment used by labels in data.inc.',
        'xor ax, ax',
        'mov ds, ax',
        'mov si, label',
        'call puts',
        'mov ax, 0x002a',
        'call print_hex16',
        'call newline',
        '',
        '; Place this declaration in data.inc:',
        "; label: db 'AX = ', 0",
      ].join('\n')),
      aid: aid('flow', 'Read the diagnostic as a sequence of representations',
        'The expected line is AX = 002A followed by CR and LF.',
        [
          node('text', 'Stored label', 'DS:SI → "AX = "', 'puts reads bytes that already represent characters. Its zero terminator controls the traversal.'),
          node('number', 'Binary word', 'AX=0x002A → "002A"', 'print_hex16 performs a representation change by selecting and encoding four nibbles.'),
          node('line', 'Cursor operation', 'newline → CR, LF', 'newline chooses the display layout after the label and value.'),
          node('device', 'Shared putc boundary', 'Every emitted byte reaches firmware', 'All three operations depend on the same low-level character request and preservation behavior.'),
        ],
        'The output side effect accumulates across calls, while each helper restores the caller state promised by its interface.',
        [{ from: 'text', to: 'number', label: 'next caller operation' }, { from: 'number', to: 'line', label: 'finish the line' }, { from: 'text', to: 'device', label: 'characters' }, { from: 'number', to: 'device', label: 'digits' }, { from: 'line', to: 'device', label: 'controls' }]),
    },
    {
      id: 'debugging-the-helpers',
      title: 'Choose a failing case that identifies the broken promise',
      paragraphs: [
        "Start with the smallest observable failure. A wrong visible character from putc suggests checking AL at entry, the AH selector at INT, and any instruction that overwrites AX before the request. Correct text followed by a failed state assertion suggests the restore path. A machine that prints once and never returns can have correct device code and a broken stack.",
        "For puts, empty input targets the position of the terminator check. An input with DF=1 targets internal direction setup and final flag restoration. A sentinel immediately after the terminator helps establish that the buffer was not modified. Distinct register high halves expose implementations that preserve only words even though the contract covers the wide registers.",
        "For print_hex16, use 0x000A to separate fixed width from letter conversion and 0xA03F to expose digit order. A formatter that adds '0' for every nibble may print punctuation for values ten through fifteen. A formatter that repeatedly shifts the source right and emits the low nibble will reverse the intended order unless it arranges a separate reversal step.",
        "Treat the machine report as evidence about named properties. It can compare output, saved CPU state, cursor positions, return behavior, and memory guards according to the published cases. It cannot prove portability to every BIOS or arbitrary memory safety for a string pointer with no bound. For additional experiments, change one condition, predict a concrete effect, and inspect that effect in a fresh run.",
      ],
      teaching: teaching(
        'Select boundary inputs that distinguish output defects from preservation and return defects.',
        'A reusable helper must work when its caller changes the input and the surrounding live state.',
        'A puts implementation prints the sample string correctly but returns DF=0 when called with DF=1. Which promise failed?',
        'Caller flag preservation failed. Forward traversal was correct internally, but the saved caller environment was not restored.',
        'Use each failed assertion to identify the specific interface property that needs repair.',
      ),
      aid: aid('compare', 'Match a symptom to the next useful observation',
        'Choose one case, then inspect the stated boundary before changing unrelated code.',
        [
          node('byte', 'Wrong glyph or no glyph', 'Inspect AH:AL at INT', 'Check whether the helper retained the supplied character and selected the intended service.'),
          node('state', 'Text correct, caller broken', 'Inspect saved widths and order', 'Check full general registers, DS/ES, flags capture, and the restore sequence.'),
          node('empty', 'Empty string emits something', 'Inspect load → test → output', 'The terminator decision must precede the character request.'),
          node('hex', '000A becomes 000:', 'Inspect values ten through fifteen', 'Numeric ASCII conversion needs the extra seven-code adjustment for uppercase hexadecimal letters.'),
          node('return', 'Text appears, completion missing', 'Inspect SP and the return frame', 'A mismatched push/pop width or early return can leave a saved value in place of the caller continuation.'),
        ],
        'A single example can satisfy the output contract accidentally. Varied inputs and state sentinels exercise the reusable behavior.'),
    },
    {
      id: 'owning-the-output-path',
      title: 'Carry the interface into your bootloader',
      paragraphs: [
        "You now own the code behind the four names used throughout the assembly foundation. The library still depends on a readable data segment, a valid stack, ordinary real-mode interrupt behavior, and a working video BIOS interface. In the next chapter, your boot stages must establish those conditions before making any diagnostic call.",
        "The loader's protected-mode transition changes the environment. Our real-mode INT 0x10 path cannot simply continue unchanged after that transition. The first C kernel will write VGA text memory and serial ports through its own output code. A small character interface remains useful, but its device-facing implementation and calling convention must match the new execution environment.",
        "The representation algorithms remain recognizable. A string traversal still needs an address, an end rule, and an ownership policy. A hexadecimal formatter still maps nibbles to a chosen digit alphabet. A line routine still needs an explicit policy for control characters or cursor positioning. Separating these algorithms from the firmware request makes the later replacement easier to explain and test.",
        "Before proceeding, finish the four executable checkpoints in the Problem view. Your saved console.asm is the concrete result: a character primitive, line composition, string traversal, and word formatter with stated preservation behavior. Optional experiments can add a bounded string writer or a two-digit byte formatter, each with a new contract and corresponding boundary cases.",
      ],
      teaching: teaching(
        'Identify which library assumptions a bootloader must establish and which ones change in protected mode.',
        'The helper implementations are now explicit. We can use them while replacing the remaining teaching setup.',
        'Which part is most directly tied to the real-mode firmware environment: nibble-to-ASCII conversion or the INT 0x10 output request?',
        'The INT 0x10 request is tied to that environment. The conversion algorithm can be retained while its output operation is adapted to a protected-mode driver and calling convention.',
        'A stable interface lets you replace an execution-environment dependency while retaining separately understood algorithms.',
      ),
      aid: aid('flow', 'What the next boot stage must prepare',
        'Follow these prerequisites before calling the library from code you boot yourself.',
        [
          node('entry', 'Establish the entry environment', 'Real mode and known segment setup', 'Use the correct instruction encoding and establish the segments your instructions depend on.'),
          node('stack', 'Provide a valid stack', 'SS:SP with enough space', 'Nested helper calls and firmware need writable stack storage and balanced return paths.'),
          node('data', 'Locate the input bytes', 'DS:SI and readable terminator', 'A label’s assembled offset must agree with the actual load address and selected data segment.'),
          node('output', 'Choose the output service', 'BIOS before the mode transition', 'Use the library while its firmware preconditions hold. After changing the execution environment, select a suitable driver interface.'),
        ],
        'The first bootloading checkpoints make these prerequisites your own executable code.'),
    },
  ],
  lab: 'boot',
  challenge: {
    title: 'Build a preserving console library',
    brief: 'Implement the four named routines in console.asm. Use lesson.asm for exploratory callers, then Submit each callable interface against its machine cases.',
    language: 'asm',
    starter: '; console.asm\n; Implement putc, then newline, puts, and print_hex16 as their checkpoints introduce them.\n',
    solution: [putcSource, newlineSource, putsSource, hexSource].join('\n\n'),
    tasks: [
      'Implement putc using the BIOS teletype interface and restore its caller state.',
      'Implement newline with CR followed by LF through putc.',
      'Implement puts as a forward zero-terminated traversal that restores the caller pointer and flags.',
      'Implement print_hex16 with exactly four uppercase digits and leading zeroes.',
    ],
    hints: [
      'Save flags before establishing DF or doing arithmetic, and restore them at the common exit.',
      'Preserve full general-register widths; save DS and ES across the firmware boundary.',
      'Test a string terminator before calling putc.',
      'Use a private copy of AX while converting nibbles into outgoing AL character codes.',
    ],
    explanation: 'The character helper owns the firmware boundary. The other helpers compose calls to it while preserving their own outer callers. Each routine returns through its original near-call frame after restoring the state it saved.',
    checks: [
      'Callable routines produce the declared output for varied supplied inputs.',
      'Full general registers, DS, ES, and the tested caller flags are preserved.',
      'String bytes remain unchanged and the empty string emits no characters.',
      'Every routine returns with a balanced stack.',
    ],
  },
  reflection: {
    prompt: 'Optional review: choose one helper and trace its input, private scratch state, nested calls, output effect, and restored caller state.',
    rubric: ['Connects each temporary change to its restoration', 'Separates output representation from firmware requests', 'Identifies the validity assumptions on pointers, stack space, and CPU mode'],
    modelAnswer: 'puts saves flags and wide general registers, clears DF, and advances a private SI through the source. It calls putc for each nonzero byte, then restores the original ESI and flags. The source must contain a readable zero before offset wrap; the stack and real-mode firmware environment must already be usable.',
  },
  sources: [
    { title: 'Intel Software Developer Manuals: instruction semantics for CALL, INT, PUSHAD, PUSHFD, POPAD, POPFD, LODS, ROL, and LOOP', url: 'https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html' },
    { title: 'NASM: BITS and operand-size overrides in 16-bit code', url: 'https://www.nasm.us/doc/nasm08.html' },
    { title: 'SeaBIOS video implementation: handle_100e and write_teletype', url: 'https://github.com/coreboot/seabios/blob/master/vgasrc/vgabios.c' },
    { title: 'SeaVGABIOS: the real-mode video firmware implementation', url: 'https://github.com/coreboot/seabios/blob/master/docs/SeaVGABIOS.md' },
  ],
  nextBuild: 'Use your understanding of calls, preservation, firmware requests, and output to build the boot stages that establish the entire machine environment.',
}];

export const assemblyOutput = outputChapters.map(chapter => ({
  ...chapter,
  legacySectionIds: chapter.sections.map(section => section.id),
  sections: chapter.sections.flatMap(section => section.id === 'preservation-contract'
    ? [...outputMechanicsSections, section]
    : [section]),
}));
