// Independent traces for the course's 386-or-newer, BITS 16, real-mode lab.
const dive = (title, paragraphs, example, pitfall, transfer, flowchart) => ({
  title, paragraphs,
  example: { title: example[0], intro: example[1], steps: example[2].map(([title, explanation, state]) => ({ title, explanation, ...(state ? { state } : {}) })), conclusion: example[3] },
  pitfalls: [{ title: pitfall[0], text: pitfall[1] }], transfer,
  ...(flowchart ? { flowchart } : {})
});
const flow = (title, intro, nodes, edges, caption) => ({ title, intro, nodes: nodes.map(([id, label, detail, kind = 'process']) => ({ id, label, detail, kind })), edges: edges.map(([from, to, label]) => ({ from, to, ...(label ? { label } : {}) })), caption });

export const assemblyDebugDepth = {
  'assembly-bits': {
    'fields': dive('Extract a field that crosses a hexadecimal boundary', [
      'A field is described by two numbers: its lowest bit position and its width. From those numbers, build a sequence of width one bits and move it left by the lowest position. For width three and position seven, the unpositioned mask is binary 111, or 7, and the positioned mask is 0x0380. This field crosses the boundary between the low and high bytes, so selecting a whole hexadecimal digit would include the wrong positions.',
      'The extraction has a useful invariant: changing any bit outside the mask cannot change the extracted value. An invariant is a statement that should stay true across all the permitted cases. It gives you a test strategy as well as an explanation. Hold the field fixed, vary unrelated neighboring bits, and check that the consumer still sees the same small integer.'
    ], ['Decode a three-bit state', 'Use the ordinary register word 0xA2D5 and assign bits 9 through 7 to the state field. Work on a copy if the complete word is needed later.', [
      ['Select the positions', 'AND with 0x0380 leaves 0x0280. The other bits disappear from the temporary result, including all upper configuration bits and the unrelated low seven bits.', '0xA2D5 AND 0x0380 = 0x0280'],
      ['Normalize the value', 'SHR by seven moves the selected positions to bits 2 through 0. The resulting ordinary integer is five, which fits the three-bit range zero through seven.', '0x0280 >> 7 = 0x0005'],
      ['Check independence', 'Changing the low byte from D5 to AA changes several unrelated bits but retains bit 7. The word 0xA2AA still extracts five, so those neighbor changes cannot affect this consumer.', '0xA2AA extracts 5 as well']
    ], 'A position mask describes storage; the shifted result describes the numerical value passed to the next operation.'], ['Confusing byte order with bit numbering', 'If this word is stored little endian, D5 occupies the lower address. That storage order does not change the mask 0x0380 or move bit 7 to a different significance.'], 'How would you extract this field after first shifting the copy right seven? Mask the shifted result with 7. Shifting alone would also bring unrelated upper bits down, so the second operation is still required.'),
    'logic': dive('Choose an update that survives repeated requests', [
      'Many bit operations implement requests to enable, disable, or invert a feature. An enable request should have the same result whether it is received once or twice. This property is called idempotence. OR with a chosen bit has it because the second request finds that bit already one. An invert request deliberately lacks this property: XOR twice restores the previous state.',
      'Separate the state being changed from the evidence used by a later branch. Logical instructions write condition flags even when every visible destination bit stays the same. An idempotent update of AX can therefore still establish new condition flags. If a branch depends on an earlier comparison, either branch before the update or establish the needed condition again afterward.'
    ], ['Enable, disable, and invert separate features', 'Let AX=0x0052. Bits 6, 4, and 1 initially hold one. Assign bit 2 to a feature that must be enabled, bit 4 to one that must be disabled, and bit 1 to one that must change state.', [
      ['Ensure the feature is enabled', 'OR AX, 0x0004 sets bit 2 without clearing bits 6, 4, or 1. Repeating the identical instruction leaves the same register value.', '0052 -> 0056 -> 0056'],
      ['Ensure another feature is disabled', 'AND AX, 0xffef clears only bit 4 in the 16-bit word. The mask must contain ones at every position that the operation should preserve.', '0056 AND FFEF = 0046'],
      ['Invert a known position', 'XOR AX, 0x0002 clears the currently set bit 1. Repeating this last request would restore bit 1, while the previous enable and disable decisions remain intact.', '0046 XOR 0002 = 0044']
    ], 'Naming each request makes the masks reviewable and explains why a duplicated enable operation differs from a duplicated toggle.'], ['Using a decimal bit number as its mask', 'Bit 4 has mask 0x0010. The number 4 selects bit 2 when interpreted as a binary mask.'], 'If the initial word is 0x0040, does the same sequence still work? Yes: enabling bit 2 gives 0x0044, disabling absent bit 4 leaves it unchanged, and toggling absent bit 1 gives 0x0046. The requests describe behavior for either prior state.'),
    'test': dive('Turn a permission sentence into an exact predicate', [
      'A predicate is a question with a true or false answer. Suppose a packed word contains READ in bit 0 and WRITE in bit 3. The mask for these two positions is 0x0009. TEST with that mask establishes whether at least one selected bit is present. It cannot distinguish read-only, write-only, and both by ZF alone, because all three produce a nonzero temporary result.',
      'To require both permissions, preserve the original word, mask a temporary copy, and compare that copy with the entire required mask. This defines the question precisely while allowing unrelated fields to coexist. Comparing the unmasked whole word with 0x0009 asks a stronger question: whether exactly those bits, and no others, are set anywhere in the word.'
    ], ['Classify three independent inputs', 'Keep mask 0x0009 fixed and test words 0x0081, 0x0089, and 0x0080. The upper bit is unrelated status that must not affect the permission decision.', [
      ['Read permission alone', '0x0081 AND 0x0009 is 0x0001. TEST makes ZF zero, so an any-permission branch succeeds, but comparing the masked copy with 9 rejects the both-permissions question.', 'any=true; all=false; none=false'],
      ['Both permissions', '0x0089 AND 0x0009 is 0x0009. Both questions now succeed even though the full input is not numerically equal to 9.', 'any=true; all=true; none=false'],
      ['Neither permission', '0x0080 AND 0x0009 is zero. ZF becomes one, and the none-permission branch succeeds. The input still contains its unrelated upper status bit.', 'any=false; all=false; none=true']
    ], 'Several inputs are needed because one value containing every selected bit cannot expose a confused any-versus-all implementation.'], ['Reading a stale zero flag', 'TEST must supply the flags consumed by the branch. An intervening arithmetic or logical instruction can establish a different ZF even though TEST preserved AX.'], 'Would an input of 0x0008 satisfy a request requiring READ and WRITE? No. It satisfies any and fails all. Writing this case beside the intended English requirement exposes the mistake before a single instruction runs.'),
    'replace-field': dive('Prove both the new value and the preserved neighborhood', [
      'A correct field replacement has two obligations. Inside the field, the result must encode the candidate value. Outside it, every original bit must remain identical. You can check the second obligation by XOR-ing old and new words: any changed position must belong to the field mask. This is stronger than checking only that extraction returns the desired value, since a destructive implementation might also erase unrelated configuration.',
      'Perform range validation before modifying the destination when rejection is the chosen policy. Otherwise a failed request can leave a half-completed update. For this register exercise, the original remains available until all checks pass. This is a small example of constructing a result separately and committing it once it satisfies the interface.'
    ], ['Replace a field spanning two nibbles', 'Bits 8 through 5 of 0xB5DB hold a four-bit field. Replace it with the unsigned candidate 3, rejecting candidates above 15.', [
      ['Validate and clear', 'Candidate 3 fits. The field mask is 0x01e0, so its 16-bit complement is 0xfe1f. Applying that complement to the original leaves 0xB41B.', 'old=B5DB; cleared=B41B'],
      ['Position and merge', 'Shift candidate 3 left five places to obtain 0x0060. OR it into the cleared word. The new field is now 3 without carrying into a neighbor.', 'B41B OR 0060 = B47B'],
      ['Verify both obligations', 'Extracting bits 8 through 5 returns 3. The difference B5DB XOR B47B is 01A0, and 01A0 AND FE1F is zero, proving that no outside bit changed.', 'field=3; outside changes=0']
    ], 'The final word passes both a value check and a preservation check, which cover different classes of implementation error.'], ['Masking away an invalid input before checking it', 'Candidate 0x13 becomes 3 after masking with 0x000f. That silently implements truncation and loses the evidence needed to reject the original candidate.'], 'If the candidate is 16, what should the destination contain after a rejecting call? The unchanged 0xB5DB. Rejection preserves the original destination and reports a defined failure outcome.'),
    'shifts': dive('Separate a stored result from information that was lost', [
      'A fixed-width shift transforms a bit pattern inside a container that does not grow. This matters even when the operation resembles multiplication. A 16-bit left shift can retain the correct low half while discarding information needed to represent the full arithmetic result. CF can describe one departing bit for a one-bit shift, but that does not make the destination a wider integer automatically.',
      'Signedness determines which interpretation is useful after the shift. Logical right shift divides an unsigned pattern by two and discards the remainder bit. Arithmetic right shift preserves a negative sign and rounds downward. If an algorithm requires truncation toward zero, the negative odd case is the discriminating test. Testing only positive even inputs makes these differences invisible.'
    ], ['Read the same source under three contracts', 'Start with AX=0x8003. Its unsigned interpretation is 32771 and its signed interpretation is -32765. Perform each operation independently from that original value.', [
      ['Shift left once', 'SHL AX, 1 stores 0x0006 and shifts an original high one into CF. The full unsigned product would be 65542, so AX retains only its low sixteen bits.', 'result=0006; CF=1'],
      ['Shift logically right once', 'SHR AX, 1 produces 0x4001, or unsigned 16385. CF receives the discarded low one, which corresponds to remainder 1 in unsigned division by two.', '32771 = 2 * 16385 + 1'],
      ['Shift arithmetically right once', 'SAR AX, 1 produces 0xC001, or -16383. Signed division yields quotient -16382 and remainder -1, so the two signed operations differ by one.', 'SAR=-16383; IDIV quotient=-16382']
    ], 'The input bits alone do not choose the arithmetic contract. Width, signedness, and rounding complete the explanation.'], ['Treating every shifted-out bit as recoverable', 'A sequence of shifts repeatedly overwrites CF. After several steps, the register and the final carry flag do not retain a history of every discarded bit.'], 'When would SAR and IDIV by two agree for a negative input? When it is even. There is then no fractional part to round differently, so both produce the same exact integer quotient.'),
    'counts-rotates': dive('Write the effective count before updating the trace', [
      'The source count and the count used by the instruction are different quantities. On the course machine, masking a shift count to five bits can turn a seemingly large request into zero. A zero effective count preserves the flags, so a following branch may depend on a condition established much earlier. This is an important case where an instruction present in the source does not create fresh arithmetic evidence.',
      'For rotations, draw a ring to show where each departing bit reenters. A one-bit ROL returns the original high bit to the low position; CF receives that departing bit too. The low result is therefore different from SHL whenever the high bit was one. Rotation also leaves ZF, SF, and PF alone, so interpreting its result needs an explicit test when a later decision asks whether the rotated value is zero.'
    ], ['Distinguish masked counts and wrapped data', 'Initialize AX=0x9001 and establish ZF=1 with a separate comparison of two equal scratch registers. Reset this initial state for each case.', [
      ['Request thirty-two shifts', 'With CL=32, SHL AX, CL uses effective count zero. AX stays 0x9001 and ZF stays one. A JZ would be taken even though AX itself is nonzero.', 'count=32 AND 31=0; AX=9001; ZF=1'],
      ['Request thirty-three shifts', 'With CL=33, the effective count is one. SHL stores 0x2002, CF becomes one, and ZF becomes zero because the new result is nonzero.', 'count=1; AX=2002; CF=1; ZF=0'],
      ['Trace a one-bit rotate', 'ROL AX, 1 from the original state wraps its high one into bit 0 and produces 0x2003. CF is one, while the preexisting ZF remains one.', 'AX=2003; CF=1; ZF=1']
    ], 'A reliable trace includes both the resulting bits and which flag values the instruction is entitled to establish.'], ['Generalizing one-bit overflow rules', 'For a nonzero count larger than one, do not infer OF from the one-bit formula. A repeatable emulator value does not turn an undefined architectural result into a contract.'], 'How can a branch ask whether 0x2003 is zero after the rotate? Use TEST AX, AX immediately before the deciding branch. That intentionally replaces stale flags with a condition about the current value.'),
    'multiply': dive('Choose whether the high half is data or an overflow report', [
      'The double-width product is useful in its own right. If a routine needs the full result, both registers belong to the result and must stay live until consumed. A live value is one a future operation still needs. Reusing DX as scratch before saving its high half can destroy a correct multiplication just as surely as choosing the wrong operands.',
      'Unsigned and signed multiplication can produce the same low word while assigning different meaning to the high word. Their overflow tests answer different questions: can the complete result be represented by the selected single-width unsigned or signed range? Neither test means the double-width result is incorrect. Instead, it tells a caller whether discarding the high half would preserve the required interpretation.'
    ], ['Produce and display a full unsigned product', 'Use unsigned AX=30000 and BX=3, then execute the one-operand MUL BX. The intended product is 90000.', [
      ['Account for both halves', 'The product is 0x00015F90, so DX receives 0x0001 and AX receives 0x5F90. CF and OF are set because the unsigned result does not fit the low word alone.', 'DX:AX=0001:5F90'],
      ['Save before display setup', 'Copy AX to a scratch register such as SI before moving DX into AX for print_hex16. The helper preserves the documented general registers, but the argument preparation itself overwrites AX.', 'SI=5F90; AX=0001'],
      ['Display in the chosen order', 'Call print_hex16 for the high half, restore AX from SI, and call it for the low half. Two four-digit fields can show the complete 00015F90 pattern without losing either component.', 'high=0001; low=5F90; value=90000']
    ], 'The multiplication and formatting stages have separate register obligations, and the trace proves the handoff between them.'], ['Using a nonzero high half as signed overflow by itself', 'For one-operand signed IMUL, -2 times 3 produces FFFF:FFFA and fits signed sixteen bits. The high half is the sign extension of the low half, so signed overflow is clear.'], 'If you want a size in bytes and the product exceeds 65535, may you keep only AX? Only if the size interface explicitly accepts modulo 65536 arithmetic. Otherwise retain a wider representation or reject the result before allocating too little space.'),
    'divide': dive('Derive the quotient bound from the original high half', [
      'Unsigned word division must satisfy a representability condition before it executes. Because DX:AX equals DX times 65536 plus AX, a high half at least as large as the divisor already supplies 65536 whole divisors. No choice of low half can reduce that quotient to the largest allowed AX value, 65535. The fit test therefore examines DX before division changes it.',
      'Keep rejection paths separate from result interpretation. Both a zero divisor and an oversized quotient cause a divide-error exception. Guard both cases using ordinary comparisons, then interpret AX and DX only on the success path. That makes a small lab program explainable without assuming a divide-error handler that it does not install.'
    ], ['Check both sides of the fit boundary', 'Choose divisor BX=3 and begin with the largest low half, AX=0xffff. Compare two independent high halves.', [
      ['Accept the last valid high half', 'DX=2 is below 3. The dividend is 2 * 65536 + 65535 = 196607. Dividing by 3 gives quotient 65535 and remainder 2, exactly fitting the unsigned word destination.', '0002:FFFF / 0003 -> AX=FFFF, DX=0002'],
      ['Reject the first invalid high half', 'DX=3 with AX=0 constructs 196608. Its quotient is 65536, so even this smallest low half overflows AX. Detect DX greater than or equal to BX before DIV.', '0003:0000 / 0003 requires quotient 10000 hex'],
      ['Check the result identity', 'For the accepted input, reconstruct 65535 * 3 + 2 = 196607 and verify remainder 2 is less than divisor 3. These are independent checks of the quotient and remainder.', 'dividend = quotient * divisor + remainder']
    ], 'The high-half rule proves unsigned quotient representability for every possible low word and nonzero word divisor.'], ['Clearing DX when the input is genuinely double width', 'Zeroing DX is correct when expanding an unsigned word in AX. It corrupts an input whose intended high half was already part of a larger dividend.'], 'Could DX=2 and AX=0xffff safely divide by 2? No. Equality of high half and divisor already proves an oversized quotient; the low half cannot make it fit.'),
    'signed-divide': dive('Check signed division with a reconstruction equation', [
      'Sign extension preserves a number while increasing its representation width. CWD expands the signed value represented by AX into the full DX:AX pair. It makes a negative word into the corresponding negative double word. The full pair is interpreted together; treating the high FFFF as a large independent positive addend loses the two’s-complement meaning.',
      'After successful IDIV, the remainder follows the dividend sign, while the quotient sign follows the combination of operand signs. These rules are easiest to verify by reconstruction: dividend equals quotient times divisor plus remainder, with the remainder magnitude smaller than the divisor magnitude. Checking only the displayed quotient can hide an incorrect assumption about the remainder or the original dividend.'
    ], ['Divide a negative value by a negative divisor', 'Represent -101 in AX as 0xff9b and represent -7 in BX as 0xfff9. The expected quotient is positive because both inputs are negative.', [
      ['Expand the intended numerator', 'CWD makes DX=0xffff. DX:AX now represents -101 in thirty-two bits. Clearing DX would turn the same low word into positive 65435.', 'signed dividend=FFFF:FF9B=-101'],
      ['Compute truncation toward zero', 'IDIV BX produces quotient 14 in AX and remainder -3 in DX. Truncating the exact positive ratio between 14 and 15 produces 14.', 'AX=000E; DX=FFFD'],
      ['Verify signs and bounds', '14 * -7 + -3 equals -101, and magnitude 3 is smaller than magnitude 7. The remainder stays negative because the original dividend was negative.', '-101 = 14 * (-7) + (-3)']
    ], 'The decimal identity explains the mathematics, while the hexadecimal words explain exactly what the registers contain.'], ['Applying the unsigned high-half comparison', 'A negative sign-extended dividend has DX=0xffff, but that does not make ordinary signed division invalid. The unsigned DX<divisor test answers a different representability question.'], 'What extra case must a routine dividing sign-extended signed words reject besides a zero divisor? AX=-32768 with divisor -1. Its mathematical quotient +32768 cannot fit signed AX, even though the input word itself is representable.'),
    'practice': dive('Give each reported word a complete data history', [
      'A multi-result report combines several small computations through shared registers. The difficult part is often preserving each result until its turn to be displayed. Write a value lifetime beside the calculation: where the value is created, which later operations might overwrite it, and where it is finally consumed. Use those lifetimes to plan which register holds each intermediate result.',
      'The course formatter displays a word’s pattern in hexadecimal. It does not know whether that pattern is a signed value, an unsigned remainder, or an extracted field. Keep those meanings in the explanation of each output position. A correct string of digits should be backed by a separate arithmetic prediction for every field in the report.'
    ], ['Plan an independent three-stage report', 'For this paper trace, extract bits 7 through 4 of 0x72A5, arithmetic-shift signed -9 right once, then divide unsigned 901 by 40. Use the actual checkpoint inputs when implementing its requested report.', [
      ['Record the extracted field', 'Masking with 0x00f0 and shifting four positions gives 0x000a. Print or save that word before reusing AX for the signed source.', 'first word=000A'],
      ['Record the signed pattern', 'Signed -9 is 0xfff7. SAR by one produces -5, represented by 0xfffb. The formatter should display FFFB; expecting a minus sign would confuse formatting with computation.', 'second word=FFFB'],
      ['Protect both division outputs', 'Prepare DX=0, AX=901, and a word divisor 40. DIV gives AX=22 and DX=21, patterns 0016 and 0015. Preserve the remainder until its output setup consumes it.', '901 = 22 * 40 + 21']
    ], 'The predicted report fields are 000A, FFFB, 0016, and 0015, each tied to a distinct input transformation.'], ['Calculate every displayed result', 'A fixed literal report can match one input while implementing none of these operations. Use a changed packed field, a negative odd shift input, and a division with a nonzero remainder to distinguish computation from imitation.'], 'If only the remainder word is wrong, which boundary should you inspect first? Check DX immediately after DIV and then every instruction before its formatter call. A correct immediate remainder directs the investigation to subsequent storage and display preparation.')
  }
};

assemblyDebugDepth['assembly-bits'].divide.flowchart = flow('A guarded unsigned word division', 'Both rejection paths finish without executing DIV. Only the success path may interpret AX and DX as results.', [
  ['input','Read DX:AX and divisor','Treat the pair as the full intended unsigned dividend.'],
  ['zero','Divisor equals zero?','No finite quotient exists for this case.','decision'],
  ['fit','Original DX below divisor?','For a nonzero word divisor, this proves that the quotient fits AX.','decision'],
  ['divide','Execute word DIV','AX receives the quotient; DX receives the remainder.'],
  ['check','Verify quotient and remainder','Reconstruct the original input and check remainder < divisor.','terminal'],
  ['reject','Report invalid division','Retain a clear failure outcome without relying on undefined flags.','terminal']
], [['input','zero'],['zero','reject','Yes'],['zero','fit','No'],['fit','divide','Yes'],['fit','reject','No'],['divide','check']], 'The checks use the original dividend. DIV replaces both halves on success, so the input must be saved separately if reconstruction is needed.');

assemblyDebugDepth['assembly-debugging'] = {
  'evidence': dive('Use competing explanations to choose the next observation', [
    'A useful hypothesis predicts something that can be checked. For a blank screen, “the emulator is broken” is too broad to guide an experiment. “The lesson returns before reaching the output request” predicts that a marker at lesson entry will appear while a marker after the branch will not. “The wrong firmware service is selected” predicts that control can reach and return from the request without producing the intended character.',
    'Keep a short evidence table in your notes: observation, explanations still possible, and next experiment. An observation can remove some explanations without identifying a unique cause. Seeing an entry marker establishes that this run reached that marker, for example, but says nothing about whether the next memory access uses the intended address. The strength of the conclusion should match the boundary you actually observed.'
  ], ['Narrow a blank-output failure in stages', 'Assume a fresh build succeeds but the expected string does not appear. Keep each experiment in a separate working copy so that its effect is clear.', [
    ['Establish an entry boundary', "Prepare AL='E' and call putc at lesson entry using the known helper. If E appears, the current guest reached this point and a known output path works.", 'E visible: entry and helper path observed'],
    ['Separate traversal from firmware', 'Restore the original routine and substitute a known short buffer containing one character and zero. If the failure persists, long-string layout is less likely, but the service selector and pointer setup remain candidates.', 'one-character input still blank'],
    ['Inspect the request inputs', 'Check the value prepared in AH immediately before INT 0x10. Finding 0x0f explains a completed query with no text. Change only that selector and predict the one-character result before running.', 'AH=0F -> query; AH=0E -> output']
  ], 'Each observation narrows the possible causes until the selected firmware operation explains the failure.'], ['Calling repeated identical runs new evidence', 'A deterministic defect can reproduce indefinitely. Another run becomes informative when it verifies a new artifact or distinguishes predictions that were previously indistinguishable.'], 'If the entry marker does not appear, does that prove boot failed? No. The marker may have been inserted into an image that was not run, or control may bypass its location. First connect the edited source, successful build, and selected running image.'),
  'listing': dive('Connect a file offset to an operand and a loaded byte', [
    'A listing answers a local question precisely: which output bytes came from this source line? To interpret that answer, record the section and offset conventions used by the tool. In a simple single-section flat binary, file offsets can be added to the load origin to locate the bytes in memory. A more elaborate multi-section layout needs its section placement rules as well, so do not silently generalize that shortcut.',
    'Use the complete assembled wrapper when comparing with the course image. The editor fragment alone omits instructions that change every later file position. Helpers and padding also occupy real bytes even when they are not the code you are currently editing. Use a known character immediate together with its opcode and listing offset to locate the intended instruction.'
  ], ['Inspect a tiny source edit at a known position', 'Suppose the listing for a completed single-section image places MOV AL, 0x4d at file offset 0x0030. This example uses a boot sector loaded at 0x7c00 with DS=0. For the browser routine program, use the same calculation with base 0x8000.', [
    ['Identify the complete encoding', 'The instruction occupies B0 4D at offsets 0x0030 and 0x0031. The opcode and immediate are different roles within one encoding, so record both bytes together.', 'file 0030: B0 4D'],
    ['Relate it to memory', 'The corresponding memory bytes are at physical 0x7c30 and 0x7c31. At this established boundary, the processor decodes an immediate move that prepares M in AL.', 'loaded address=7C00+0030=7C30'],
    ['Verify a new artifact', 'Changing M to N should change the immediate to 4E while preserving B0 and the two-byte instruction length. Assemble again and compare the new bytes before interpreting the next run.', 'fresh file 0030: B0 4E']
  ], 'The comparison links a specific textual edit to a specific byte change at a specific runtime position.'], ['Expecting a disassembler to recover source labels', 'A decoder can produce an instruction from B0 4E without knowing that the source called the character a marker. Symbol names, comments, and source-level intention require the listing or source.'], 'If adding another instruction before this one changes its file offset, is the old address still a valid breakpoint? Not necessarily. Recompute the location from the new listing; a stale address may stop inside a different instruction even when the marker byte remains present.'),
  'bytes': dive('Make control flow define which stored bytes become instructions', [
    'The same memory can be examined through different interpretations. A byte viewer shows numbers, a string routine treats selected numbers as characters, and the instruction decoder groups bytes according to opcodes and machine mode. None of these interpretations is stored as an intrinsic type beside each byte in a flat boot image. The current operation and its starting address supply the interpretation.',
    'This makes layout a correctness concern. A label preceding data is an address name for the assembler; it does not stop fall-through execution. To put inline data between two executable pieces, ordinary execution needs a branch around it or another deliberate transfer. Conversely, jumping over bytes does not make them inaccessible as data: a memory-reading instruction can still address them.'
  ], ['Place data behind a deliberate branch', 'Consider a miniature at file offset 0x0030 containing EB 04 followed by the data bytes 90 90 00 7F, then an instruction at offset 0x0036. Use the course 16-bit decoding environment.', [
    ['Decode the entry instruction', 'EB 04 is a short jump. Its following address is 0x0032, and adding four reaches 0x0036. No byte in the intervening four-byte data area is fetched as an instruction along this path.', '0030 -> 0036'],
    ['Read the same storage as data', 'A separate routine can address the four-byte area beginning at 0x0032 and observe 0x90 as its first element. That data read does not execute a NOP merely because 0x90 can encode one.', 'data[0]=90; data[2]=00'],
    ['Explain a fall-through defect', 'Removing the jump changes the path into the data. Some bytes may decode successfully, which can delay visible failure, but successful decoding does not supply the intended program behavior.', 'layout remains bytes; path determines use']
  ], 'The example separates storage from interpretation and shows why valid instruction encodings are weak evidence of a valid execution path.'], ['Assuming zero ends instruction execution', 'A zero byte terminates a string only because the string routine checks it. End execution with the required return or deliberate halt path.'], 'Could a counted data reader consume all four bytes including zero? Yes. Its stopping rule is the supplied length. A null-terminated reader of the same area would stop at the third byte, demonstrating that the consumer defines the representation.'),
  'origin': dive('Keep file position, assumed address, and physical address separate', [
    'Three numbers often look similar enough to be confused: a byte’s file offset, the address NASM assigns to its label, and the physical address selected during execution. They coincide only under specially chosen conventions. Write each number separately before combining them. ORG affects the assembler’s address calculation; the loader determines where the file arrives; the segment and offset together determine where a real-mode memory instruction looks.',
    'Relative transfers can conceal an origin mismatch because the same origin is added to both branch endpoints and cancels when their difference is computed. An absolute data pointer does not enjoy that cancellation. Thus a routine can follow apparently correct control flow while reading an unrelated location. This diagnostic pattern points to the different address calculations used by relative branches and absolute pointers.'
  ], ['Locate one byte under two coherent conventions', 'A message begins at file offset 0x0123 and firmware places the image at physical 0x7c00. Its first byte is therefore physically at 0x7d23, regardless of the source origin directive.', [
    ['Use the boot-sector convention', 'ORG 0x7c00 makes the label 0x7d23. With DS=0 and SI holding that label, DS * 16 + SI selects physical 0x7d23.', '0000:7D23 -> physical 7D23'],
    ['Describe a different coherent scheme', 'A separately designed program could use ORG 0 and DS=0x07c0, with SI=0x0123. The segment contribution 0x7c00 plus that offset reaches the same byte.', '07C0:0123 -> physical 7D23'],
    ['Expose the mixed scheme', 'Changing only ORG to zero in this boot-sector example leaves DS=0. SI=0x0123 then reads physical 0x0123, leaving the loaded message at 0x7d23 untouched, despite unchanged relative jumps.', '0000:0123 -> wrong physical 0123']
  ], 'Both coherent conventions can identify the same storage, but mixing pieces of them breaks the agreement. The browser routine wrapper uses the same zero-segment convention with ORG 0x8000, matching its separate loader.'], ['Changing the origin to move the binary', 'ORG neither instructs firmware to load elsewhere nor prepends memory-sized padding. A new physical destination requires a loading or copying operation outside the directive.'], 'If you add two bytes before the message, what changes? Its file offset, assembled label, and correct loaded physical address all increase by two. The actual segment setup stays unchanged unless your program explicitly changes it.'),
  'relative': dive('Calculate both forward and backward displacements from the endpoint', [
    'The base for a relative branch is the first address after its complete encoding. This convention lets the processor combine its already advanced instruction position with a signed displacement. To check a branch, use four columns: instruction start, encoded length, signed displacement, and computed target. If any one of those is guessed incorrectly, a plausible-looking destination can still be wrong.',
    'A source label removes the need to hand-maintain that displacement, but it does not remove the need to understand it when reading bytes. When earlier instructions grow, the assembler recomputes distances. A forced short branch is also a range assertion: its destination must remain within the signed-byte reach measured from the following address. A layout change can make that assertion false even if the target label still exists.'
  ], ['Decode opposite directions around one base', 'Use a short jump beginning at offset 0x0040. Its two-byte encoding ends immediately before 0x0042, which is the relative base in both examples.', [
    ['Reach a forward target', 'For target 0x0060, subtract 0x0042 from 0x0060 to get 0x1e, or +30. Bytes EB 1E reach the target after adding that displacement to the following position.', '0042 + 001E = 0060'],
    ['Reach a backward target', 'For target 0x0035, the displacement is -13. Its signed-byte representation is 0xf3, so EB F3 reaches 0x0035.', '0042 + (-13) = 0035'],
    ['Check a range edge', 'The largest positive short displacement is +127. From base 0x0042 it reaches 0x00c1. Target 0x00c2 would need +128 and therefore cannot use this short form.', 'maximum forward target=00C1']
  ], 'The same arithmetic explains forward branches, backward loops, and the exact boundary at which a short encoding stops fitting.'], ['Subtracting from the instruction start', 'Using 0x0040 as the base shifts the computed destination by two bytes. The correct subtraction includes the whole encoding length before applying the displacement.'], 'If both branch and target are loaded 0x7c00 bytes higher, must these displacement bytes change? No. Adding the same origin to both cancels in target minus following address. Absolute pointers in the same image need their own address calculation.'),
  'bios-service': dive('Treat a firmware request as a complete input and output contract', [
    'An interrupt vector identifies an entry point, while the service selector chooses a particular operation inside that interface. The distinction resembles calling a dispatcher with an operation number. Using the correct vector with the wrong selector can be a completely valid request that produces the wrong kind of result. A successful return from firmware therefore does not prove a character-output request was made.',
    'Raw firmware calls also have outputs. If an earlier call returns information in a register that the next request uses as an input, prepare that register again. The course helper putc wraps its firmware use with a stronger preservation promise, but replacing the helper with INT 0x10 means accepting responsibility for the raw interface at every call site. Keep the established text mode and page-zero course assumptions explicit.'
  ], ['Distinguish a query result from a printable argument', 'Suppose a routine wants to display R, whose code is 0x52, but first performs the video-mode query in the course text-mode environment.', [
    ['Prepare the query', 'AH=0x0f selects video-mode information. This service returns video information in registers and leaves the intended R unprinted.', 'entry AX=0F52; requested operation=query'],
    ['Observe returned information', 'For a mode-3, eighty-column, page-zero SeaBIOS state, the query returns AL=3, AH=80 decimal, and BH=0. The old R byte has been replaced by a mode number.', 'returned AL=03; AH=50 hex; BH=00'],
    ['Build a fresh output request', 'Prepare both AH=0x0e and AL=0x52 before the next INT 0x10, along with the course BX input. Changing only AH would leave the returned mode byte in AL.', 'new AX=0E52; intended character=R']
  ], 'The repaired request names the desired service and rebuilds every argument that the earlier query may have changed.'], ['Assuming an entry point has only one meaning', 'INT 0x10 dispatches the selected operation, which can replace AL with a return value. Interpret registers using the selected service contract.'], 'If two direct character requests should print RS, which values must differ and which must be reestablished? AL changes from 0x52 to 0x53; AH must describe teletype output for each request. Do not infer preservation solely from the first character appearing.'),
  'strings': dive('Use the stopping rule to prove which addresses are read', [
    'A traversal needs both an address progression and a termination rule. DF controls progression for LODSB, but it does not establish a boundary. A zero terminator establishes a boundary only for a consumer that encounters and checks it. These are independent obligations. Forward and reverse traversals can read the same array correctly while requiring different starting addresses and different stopping conditions.',
    'For a counted traversal, the count is the maximum number of permitted loads, so handle zero before entering a body that decrements afterward. For a null-terminated traversal, distinguish loads from output requests: reading the terminator is a successful memory operation, but it should cause no output. A trace with separate read and print counts exposes extra output or a missing final check.'
  ], ['Compare forward termination with bounded reverse reading', 'Assume bytes 4D 4F 4F 4E 00 occupy offsets 0x7200 through 0x7204 in DS=0. They represent MOON followed by zero.', [
    ['Walk forward to the terminator', 'Starting SI=0x7200 with DF=0 performs five loads. Four nonzero loads request output, and the fifth loads zero, advances SI to 0x7205, then takes the stop branch.', 'loads=5; prints=4; final SI=7205'],
    ['Choose a reverse boundary', 'For a separate reverse exercise, start at 0x7203 with DF=1 and count four. Loads read N, O, O, M in that order. The existing trailing zero is behind the starting direction and cannot stop this walk.', 'addresses: 7203,7202,7201,7200'],
    ['Finish with the caller contract', 'After four reverse loads, SI is 0x71ff and the count is zero. Clear DF before returning to code that expects forward string operations. The array bytes remain unchanged throughout.', 'output=NOOM; return DF=0']
  ], 'The trace explains the final pointer, the number of reads, and the visible characters using separate state changes.'], ['Calling puts to implement a reverse reader', 'The supplied puts establishes forward direction internally. Its contract is a forward null-terminated string, so it cannot stand in for the bounded reverse loop described here.'], 'What happens for a forward empty string at 0x7200? One load reads zero and advances SI once, but no character is printed. For a counted reverse operation with count zero, a correct entry guard performs no load at all.'),
  'experiments': dive('Preserve the state that your observation is meant to measure', [
    'Instrumentation is extra code inserted to reveal behavior. Because it executes on the same machine, it can alter the very registers or flags under investigation. An output helper that preserves its inputs still cannot undo changes you made while preparing them. Decide which values are live at the observation point, save those values before preparing a marker, and restore them before resuming the original logic.',
    'Choose an experiment whose two possible outcomes have different implications. A marker before a branch and another on one destination can show which path was taken, but only if the marker preparation preserves the branch condition. If it changes that condition, the experiment’s branch outcome describes the changed condition produced by its own instrumentation. State this limit before treating an apparent fix as evidence.'
  ], ['Insert a marker between comparison and branch', 'Suppose AX contains a loaded word, CMP AX, 0 establishes the condition, and JZ should select the zero case. You want to emit ? between the comparison and the branch.', [
    ['Save the argument destination', 'PUSH AX preserves the complete word before MOV AL overwrites its low byte. Neither PUSH AX nor MOV AL changes the comparison flags in this sequence.', 'saved AX on stack; comparison flags retained'],
    ['Prepare and emit the marker', "MOV AL, '?' prepares the marker, then CALL putc prints it. The course helper preserves general registers and flags, including the flags established by CMP.", 'marker visible; saved comparison flags retained'],
    ['Restore and decide', 'POP AX restores the original word without changing those flags. JZ now consumes the original comparison result. The extra push and pop are balanced before either branch continues.', 'AX restored; SP restored; JZ uses original CMP']
  ], 'The marker adds an observation while preserving the data, stack position, and branch condition needed by the original path.'], ['Using XOR AX, AX to prepare a diagnostic zero', 'XOR would overwrite both AX and the zero flag. A following JZ could then always take the zero branch, making the instrumented program appear to confirm a false explanation.'], 'Does this marker prove exact timing stayed unchanged? No. It adds calls, stack accesses, and firmware work. It is appropriate for this deterministic control-flow question, but timing-sensitive faults require observations designed around their timing effects.'),
  'halt': dive('Distinguish completion, waiting, and repeated execution', [
    'A stable display records the visible output left by the program. A program can leave the same character visible after returning successfully, while sleeping in HLT, while repeatedly executing a jump, or after transferring somewhere unintended. Give completion its own evidence, such as a reached return boundary or a known marker before the deliberate halt path.',
    'The workbench wrapper uses CLI, HLT, and a branch back into its halt sequence. That is a deliberate place to preserve the final display. With ordinary maskable interrupts disabled, an ordinary periodic timer interrupt remains masked there. Non-maskable events and reset are different architectural possibilities, so retain those possibilities when explaining the course’s chosen stop behavior.'
  ], ['Compare two programs with the same final screen', 'Both independent routines display K exactly once. One returns to the supplied wrapper. The other enters a short jump to its own address after displaying K.', [
    ['Observe the common output', 'Each run leaves K visible. That observation proves an output request occurred, but it does not distinguish what happened after the request returned.', 'both displays: K'],
    ['Follow the successful return', 'The first routine balances its stack and returns. The wrapper reaches its known CLI and HLT path, so stopped ordinary execution is consistent with intended completion.', 'lesson return -> wrapper halt'],
    ['Follow the repeated branch', 'The second routine keeps executing its self-directed jump. It does no additional output, but its architectural path continues through the same control-transfer instruction on every iteration.', 'jump -> same jump -> same jump']
  ], 'The difference is in the execution path after output, which requires control-flow evidence beyond a screenshot.'], ['Adding STI to make the display seem alive', 'Interrupts do not create a progress display automatically. Changing interrupt policy also introduces handler and stack assumptions, and it may hide the original control-flow question.'], 'What is the first useful question if the workbench says powered on but no text changes? Ask whether the routine was expected to emit more text or had already completed. Then inspect a known execution boundary to establish the guest’s current path.'),
  'mode': dive('Decode one immediate move under two different defaults', [
    'Assembler mode and processor mode are separate inputs to the build-and-run pipeline. NASM uses BITS to select encoding defaults. The processor uses its architectural execution state to decode the resulting stream. A disagreement can change both operand width and where the next instruction starts, so mode errors often produce symptoms that look unrelated to the line where the wrong directive appeared.',
    'Using a wider register does not itself require changing the machine’s overall mode. In BITS 16 code for the course’s 386-or-newer CPU, NASM can encode a 32-bit operand with the appropriate size prefix. This preserves the agreement that unprefixed instructions have sixteen-bit defaults. Track operand size, address size, and execution mode separately in the trace.'
  ], ['Compare the bytes for a 32-bit constant', 'The intended operation is MOV EAX, 0x12345678. Compare an encoding prepared for sixteen-bit defaults with one prepared for thirty-two-bit defaults.', [
    ['Encode for the current environment', 'Under BITS 16, NASM uses operand-size prefix 66 before B8 and the four immediate bytes. The complete encoding is 66 B8 78 56 34 12.', '16-bit defaults: 66 B8 78 56 34 12'],
    ['Describe the incompatible assumption', 'Under BITS 32, the same intended EAX operation needs no 66 prefix, giving B8 78 56 34 12. Merely writing that directive has not changed the guest’s real-mode defaults.', '32-bit defaults: B8 78 56 34 12'],
    ['Decode with actual guest state', 'A normal sixteen-bit decoder starting at the unprefixed B8 consumes 78 56 as a word immediate, yielding AX=0x5678. Bytes 34 12 then decode as a following XOR AL, 0x12, creating a second executed instruction.', 'wrong path: MOV AX,5678; XOR AL,12']
  ], 'One omitted prefix changes instruction boundaries as well as the loaded value, explaining why a successful build can still execute an unintended program.'], ['Treating BITS as a runtime transition', 'The directive does not load descriptors, change CR0, or reload the code segment. The later protected-mode chapter builds those processor-state changes explicitly.'], 'Can a sixteen-bit real-mode program on this CPU use EAX for a calculation? Yes, with a compatible encoding and the instruction’s other requirements satisfied. That does not give it protected-mode segmentation or a different default address size.'),
  'handoff': dive('Turn wrapper conveniences into named boot responsibilities', [
    'The final assembly exercise is a boundary between using an environment and constructing one. List each promise beside the code that currently establishes it: segment values, usable stack, clear DF, chosen display mode, callable helpers, and a valid continuation after the lesson returns. A correct routine depends on those promises even when its body is only a few instructions long.',
    'A responsibility transfers safely when the replacement establishes the same precondition before the dependent code runs. Removing every convenience simultaneously makes a blank result ambiguous again. Transfer one responsibility, retain a small known observation, and explain the new entry and exit conditions. The boot signature and fixed image size remain image-format obligations, while segment setup and stack validity are runtime obligations.'
  ], ['Verify a general reader before owning its setup', 'Use an independent supplied buffer containing GO followed by zero. The routine must read the buffer, make direct video requests for its nonzero bytes, and return with the course’s required state intact.', [
    ['Name the entry promises', 'DS:SI identifies G, DF is clear, and the stack contains a valid return address. LODSB can therefore read the intended first byte and advance toward O without the lesson reimplementing the wrapper.', 'bytes=47 4F 00; direction=forward'],
    ['Follow all three loads', 'The first two loads request G and O through the chosen teletype service. The third loads zero and reaches the return path before issuing another output request. No instruction needs to alter the buffer.', 'loads=3; requests=2; buffer unchanged'],
    ['Change the representation input', 'Replace the data with a single zero and run a fresh build. The same traversal returns without requesting a character. This distinguishes a general reader from a program that happens to print GO.', 'empty input: loads=1; requests=0']
  ], 'The general traversal is established before its surrounding initialization becomes your responsibility in the bootloader chapter.'], ['Carrying RET into a new entry contract unchanged', 'The course wrapper calls the lesson, so a return address exists. A firmware entry point that was reached by a jump does not automatically have the same callable-routine contract. Design its continuation explicitly.'], 'Which promise would you investigate first if a copied routine walks backward in the new bootloader? Check DF before its first string instruction, then verify the starting pointer. A working course run establishes the routine’s behavior under the wrapper’s documented entry state. Reestablish those required conditions in the new loader.')
};

assemblyDebugDepth['assembly-debugging'].strings.flowchart = flow('A bounded forward string reader', 'This conceptual extension adds a maximum read count to the supplied terminator-based traversal. Check the count before every load.', [
  ['setup','Set DS:SI, DF, and limit','Point to the buffer, select forward direction, and state the maximum permitted reads.'],
  ['remaining','Read budget remains?','Check before touching the next byte.','decision'],
  ['load','Load byte and consume budget','LODSB updates AL and SI; account for this successful read.'],
  ['zero','Loaded byte equals zero?','The terminator ends reading without a character request.','decision'],
  ['emit','Request output for this byte','Prepare the firmware inputs or use the documented helper.'],
  ['done','Return successfully','The terminator was encountered inside the permitted range.','terminal'],
  ['exhausted','Report missing terminator','The budget ended before a valid stop marker was found.','terminal']
], [['setup','remaining'],['remaining','load','Yes'],['remaining','exhausted','No'],['load','zero'],['zero','done','Yes'],['zero','emit','No'],['emit','remaining']], 'The backward arrow repeats the read decision. An empty string follows the first zero branch and produces no output; a missing terminator reaches an explicit bounded failure.');
