#!/usr/bin/env python3
"""Generate the personal site's static responsive images without changing originals.

Requires Pillow with WebP support: python3 -m pip install Pillow
Run from any directory: python3 scripts/generate-site-images.py
Generated native-size screenshots are pixel-exact lossless WebP. Smaller images
use Lanczos resizing and lossless encoding to keep text and diagram edges clear.
"""

import hashlib
from io import BytesIO
import json
from pathlib import Path

from PIL import Image, features


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'public/assets/optimized'
PROJECTS = ('proto-rs', 'wirebyte', 'zenos', 'lamp', 'sudoku-solver', 'chinar')
ARTICLES = {'gsoc': 'Google Summer of Code logo', 'vlc': 'VLC media player traffic cone logo'}


def generate(source, name, widths):
    with Image.open(source) as original:
        image = original.convert('RGBA' if 'A' in original.getbands() or 'transparency' in original.info else 'RGB')
        native_width, native_height = image.size
        variants = []
        for width in sorted({min(value, native_width) for value in widths} | {native_width}):
            height = max(1, round(native_height * width / native_width))
            resized = image if width == native_width else image.resize((width, height), Image.Resampling.LANCZOS)
            buffer = BytesIO()
            resized.save(buffer, format='WEBP', lossless=True, method=6, exact=True)
            body = buffer.getvalue()
            # Verify every derivative's codec preserved the intended pixel data.
            with Image.open(BytesIO(body)) as decoded:
                assert resized.convert('RGBA').tobytes() == decoded.convert('RGBA').tobytes(), source
            fingerprint = hashlib.sha256(body).hexdigest()[:12]
            filename = f'{name}-{width}.{fingerprint}.webp'
            variants.append({'src': f'/assets/optimized/{filename}', 'filename': filename,
                             'width': width, 'bytes': len(body), 'body': body})
        native = variants[-1]
        # Resampling sharp text can add colors and make a smaller lossless image
        # larger than its native original. Never select a more expensive resize.
        variants = [item for item in variants if item['width'] == native_width or item['bytes'] < native['bytes']]
        for item in variants:
            (OUTPUT / item['filename']).write_bytes(item['body'])
        current = {item['filename'] for item in variants}
        for old in OUTPUT.glob(f'{name}-*.webp'):
            if old.name not in current:
                old.unlink()
        print(f'{source.relative_to(ROOT)}: {source.stat().st_size:,} → {native["bytes"]:,} bytes at native resolution; responsive widths {[item["width"] for item in variants]}')
        return {'src': native['src'], 'width': native_width, 'height': native_height,
                'srcSet': ', '.join(f'{item["src"]} {item["width"]}w' for item in variants)}


def main():
    if not features.check('webp'):
        raise SystemExit('Pillow needs WebP support to generate these assets.')
    OUTPUT.mkdir(parents=True, exist_ok=True)
    projects = {name: generate(ROOT / f'src/assets/{name}.png', name, (640, 1100)) for name in PROJECTS}
    articles = {}
    for name, alt in ARTICLES.items():
        articles[f'/assets/{name}.png'] = {**generate(ROOT / f'public/assets/{name}.png', name, (250, 500)), 'alt': alt}
    content = '// Generated by scripts/generate-site-images.py; keep original PNGs as the source.\n'
    content += 'export const projectImages = ' + json.dumps(projects, indent=2) + ';\n\n'
    content += 'export const articleImages = ' + json.dumps(articles, indent=2) + ';\n'
    (ROOT / 'src/constants/siteImages.js').write_text(content)


if __name__ == '__main__':
    main()
