// Additional original tutorials that extend the first memory handbook.
const ref = (label, url, section) => ({ label, url, section });
const intel = ref('Intel architecture manuals', 'https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html', 'Real-address mode, address formation, and paging');
const osc = ref('Operating System Concepts, tenth edition: Main Memory', 'https://www.os-book.com/OS10/slide-dir/PPTX-dir/ch9.pptx', 'Chapter 9: effective access time, hashed tables, and inverted tables');
const ostep = (label, file, section) => ref(`OSTEP: ${label}`, `https://pages.cs.wisc.edu/~remzi/OSTEP/${file}.pdf`, section);
const p = (...paragraphs) => ({ type: 'prose', paragraphs });
const table = (caption, columns, rows) => ({ type: 'table', caption, columns, rows });
const trace = (caption, columns, rows) => ({ type: 'trace', caption, columns, rows });
const code = (title, language, code, notes) => ({ type: 'code', title, language, code, notes });
const exercise = (title, prompt, tasks, solution, checks) => ({ type: 'exercise', title, prompt, tasks, solution, checks });
const topic = (id, sectionId, title, intro, blocks, references) => ({ id, sectionId, title, intro, blocks, references });

export const memoryFurtherHandbook = {
  'memory-discovery': [
    topic('a20-preserve-probe-restore', 'a20', 'Implement an A20 probe that restores both possible memory states', [
      'Before a legacy BIOS loader uses RAM above 1 MiB, it must establish the address behavior promised by its machine profile. A20 masking clears address bit 20 on relevant legacy hardware. A controlled alias probe can distinguish two independent bytes from two addresses naming the same byte.',
      'The routine below runs in 16-bit real mode before paging. Its platform contract reserves both probe bytes and the stack, permits temporary writes there, and excludes other writers during the test. The example locations are part of this declared test environment; they are not universally free BIOS scratch memory.'
    ], [
      table('Derive both probe addresses from segment and offset', ['Name', 'Real-mode address', 'Linear address', 'With bit 20 cleared'], [['Low','0000:0600','0x00000 + 0x0600 = 0x000600','0x000600'],['High','FFFF:0610','0xFFFF0 + 0x0610 = 0x100600','0x000600']]),
      code('Original bounded save, probe, restore routine', 'asm', 'bits 16\n; AX = 1 if independent, AX = 0 if aliased.\n; All other registers and original FLAGS are preserved.\na20_probe:\n    pushf\n    cli\n    push ds\n    push es\n    push si\n    push di\n    push bx\n    push cx\n    xor ax, ax\n    mov ds, ax\n    mov ax, 0xffff\n    mov es, ax\n    mov si, 0x0600\n    mov di, 0x0610\n    mov bl, [si]\n    mov bh, [es:di]\n    mov byte [si], 0x35\n    mov byte [es:di], 0xca\n    xor cx, cx\n    cmp byte [si], 0x35\n    jne .restore\n    inc cx\n.restore:\n    mov [es:di], bh\n    mov [si], bl\n    mov ax, cx\n    pop cx\n    pop bx\n    pop di\n    pop si\n    pop es\n    pop ds\n    popf\n    ret', [
        'PUSHF precedes CLI so POPF restores the caller’s interrupt-enable state. The routine requires a valid stack whose bytes do not overlap either probe.',
        'DS = 0 and ES = 0xFFFF select the two segment bases. SI and DI supply offsets differing by 0x10 so the final byte addresses differ by exactly 0x100000.',
        'BL and BH save the original low and high bytes before either location is modified. In the alias case, both saved values describe the same original storage.',
        'The high write changes the low read only when the names alias. CX retains the boolean observation while both writes are undone.',
        'Restoring the high name first and the low name second is valid for independent storage and for aliased storage. AX receives the result before the saved CX is restored.'
      ]),
      p('Preservation is part of correctness. Suppose independent bytes originally contain 0x91 and 0x27. After the markers, they contain 0x35 and 0xCA, and the low read reports independence. Restoration writes 0x27 high and 0x91 low. In the alias case, both saves read the same original byte, the second marker replaces the first marker, and both restoring writes restore that original value.',
        'Disabling maskable interrupts narrows interference but does not exclude NMI, DMA, or platform firmware activity. The boot environment must ensure that these specific bytes are safe to borrow. Running an arbitrary probe after another subsystem owns the region violates that ownership even when the original byte is eventually restored.',
        'An enable workflow should first probe because some firmware already enables A20. If the bytes alias, use an enable method supported by the platform, then probe again. A BIOS service, system-control port, and keyboard-controller transaction have different contracts. A legacy keyboard-controller method needs bounded status polling and preservation of unrelated control bits; an absent controller must produce a timeout instead of an infinite boot loop.',
        'Keep an explicit attempt limit and record the method and observation. Report failure if every permitted method leaves aliasing. Do not publish high-memory ranges to the allocator until the final probe succeeds. Modern environments can define different A20 behavior, so the relevant firmware and processor contract takes precedence over legacy assumptions.'),
      exercise('Prove the restoration order', 'The low byte initially holds 0x6D. If the two addresses are independent, the high byte holds 0xE2; otherwise both names refer to the low byte.', ['Trace BL, BH, and the observed low byte for both cases.', 'Give the final AX and memory contents.', 'Explain why saving the high byte after writing the low marker would be incorrect.'], ['Independent: BL = 0x6D, BH = 0xE2, observed low = 0x35. Aliased: BL = BH = 0x6D, observed low = 0xCA.', 'Independent returns AX = 1 and restores 0x6D/0xE2. Aliased returns AX = 0 and restores the one byte to 0x6D.', 'In the alias case, the later save would capture a marker instead of the original byte. The saved state would no longer describe the entry condition.'], ['AX is 1 only for independent bytes.', 'Every borrowed byte regains its original value.'])
    ], [intel, ref('Intel Pentium II system programming reference', 'https://download.intel.com/design/PentiumII/manuals/24400101.pdf', 'Section 3.2.8: A20M compatibility signal'), ref('OSDev companion: A20 line', 'https://wiki.osdev.org/A20_Line', 'Platform enable methods and testing, interpreted under the stated machine contract')]),
    topic('boot-reservation-lifetime-ledger', 'boot-info', 'Bootstrap allocator metadata without allocating its own storage twice', [
      'A physical allocator needs metadata before it can safely allocate its first frame. That metadata itself occupies RAM and must be reserved. Break this dependency with a small early reservation mechanism whose storage and lifetime are already known, then transfer its complete ownership ledger to the final allocator.',
      'Use half-open physical intervals throughout the handoff. Keep usable-memory discovery separate from reservation records, and preserve a reason and release condition for every reservation. Reclaiming loader storage becomes a proved state transition after all needed information has moved to kernel-owned storage.'
    ], [
      table('A boot ledger with explicit release conditions', ['Reservation', 'Physical interval', 'When release becomes legal'], [['Kernel image including BSS','[0x100000,0x12B900)','Retained for kernel lifetime in this model.'],['Copied allocator bitmap','[0x12C000,0x12D000)','Retained while the allocator uses it.'],['Loader boot-information buffer','[0x9000,0xA500)','After recursive payload copying and retirement of all pointers into it.'],['Temporary page tables','A recorded set of complete frames','After the active hierarchy and all software/hardware references have moved.'],['Loader stack','An explicitly bounded low-memory interval','After switching stacks and returning no further into loader frames.']]),
      p('For a 16 MiB managed physical window and 4 KiB frames, a bitmap indexed by every possible frame needs 4096 bits, or 512 bytes. Reserve a whole backing frame even though the bitmap uses only part of it. The example kernel image ends inside frame 0x12B, so its rounded reservation ends at 0x12C000. The next aligned frame [0x12C000,0x12D000) can hold the bitmap if the normalized firmware map declares it usable and no other reservation overlaps it.',
        'An early allocator can scan canonical usable intervals in ascending order and subtract the ledger’s occupied intervals. Pick the first aligned span large enough for the requested metadata, append its reservation to the ledger immediately, and only then initialize the bytes. The ledger itself can initially live in a fixed-capacity array reserved with the loader or kernel. Exhausting that array is a boot error; silently dropping a reservation would make later ownership incorrect.'),
      trace('Two-phase transition to the final bitmap', ['Phase', 'Action', 'Invariant established'], [['Prepare','Reserve kernel, stacks, tables, boot buffers, modules, and bitmap storage.','Every existing owner appears in the ledger.'],['Initialize','Set every bitmap bit to unavailable, including padding bits.','Unknown addresses remain protected.'],['Release candidates','Clear bits only for complete usable frames outside all ledger intervals.','No live owner is returned by allocation.'],['Copy handoff data','Copy validated headers and every retained pointed-to payload.','Kernel data no longer depends on reclaimable loader bytes.'],['Retire old references','Update pointers, mappings, and active stacks as needed.','Former buffers are unreachable by future legitimate accesses.'],['Reclaim deliberately','Release eligible whole frames after checking all remaining reservations.','Reclamation respects overlapping ownership.']]),
      p('A shallow structure copy can preserve dangling physical pointers. If a header contains a pointer to a command line, module list, memory map, or framebuffer descriptor, copying only the header leaves those dependencies in loader-owned storage. Walk the accepted format, bound each nested extent, copy the required payloads, and rewrite pointers or store stable offsets. Hardware resources such as a framebuffer remain external resources; copying their descriptor does not copy the hardware itself.',
        'Overlapping reservations require union semantics. If two owners share a page, releasing one owner’s interval must leave that page unavailable while the other reservation remains. A single boolean reserved bit loses the reason information needed to make this decision. Keep the interval ledger until reclamation is complete, or transfer equivalent ownership/reference metadata into the final allocator.',
        'The final allocator can discard early bookkeeping only after it represents every live allocation and the kernel no longer calls the early allocator. Document that cutover. Continuing to allocate through both mechanisms creates two authorities over the same RAM unless their pools are explicitly disjoint.'),
      exercise('Reclaim a shared boundary page', 'Boot information occupies [0x9000,0xA500), and a live module descriptor occupies [0xA400,0xA900). All bytes are firmware-usable.', ['Find the frames covered by each reservation.', 'After copying the boot information, decide which frames can be released.', 'Find the bitmap size for a 64 MiB managed physical window.'], ['Boot information occupies PFNs 9 and 10. The module descriptor occupies PFN 10.', 'PFN 9 can be released after its references retire. PFN 10 remains reserved until the module descriptor also moves or becomes dead.', '64 MiB / 4096 = 16384 frames; one bit per frame requires 2048 bytes, still one backing frame.'], ['Only PFN 9 is reclaimed at the first handoff.', 'The 64 MiB bitmap uses 2048 bytes.'])
    ], [ref('Linux boot-time memory management', 'https://docs.kernel.org/core-api/boot-time-mm.html', 'Memory regions, reservations, and transition to the page allocator'), ref('Philipp Oppermann: allocating frames', 'https://os.phil-opp.com/allocating-frames/', 'First-edition discussion of occupied boot regions and frame ownership')])
  ],
  'physical-memory': [
    topic('buddy-seed-arbitrary-ranges', 'initialization', 'Seed buddy free lists from irregular firmware ranges', [
      'The buddy split-and-merge algorithm assumes its input blocks already satisfy order alignment and ownership boundaries. Firmware rarely hands the allocator one perfectly aligned power-of-two arena. Initialization must decompose each normalized free run into legal blocks without extending a block over a reserved page or hole.',
      'This teaching policy uses absolute frame-number alignment within a zone. An order-k block starts at a PFN divisible by 2^k and spans exactly 2^k frames. A zone can contain several initial blocks of different orders; a maximum order caps the largest block the implementation represents.'
    ], [
      code('Choose the largest legal block at the front of a run', 'c', '#include <stdint.h>\n#include <stdbool.h>\n\nbool next_buddy_seed(uint32_t first, uint32_t end,\n                     unsigned maximum_order,\n                     unsigned *order_out, uint32_t *next_out) {\n    if (first >= end || end > (1u << 20) || maximum_order > 20)\n        return false;\n    unsigned order = 0;\n    while (order < maximum_order) {\n        uint32_t larger = 1u << (order + 1);\n        if ((first & (larger - 1u)) != 0 || larger > end - first)\n            break;\n        ++order;\n    }\n    *order_out = order;\n    *next_out = first + (1u << order);\n    return true;\n}', [
        'The caller passes a nonempty free PFN interval and writable output pointers. This model limits PFNs to a 4 GiB physical window of 4 KiB frames and leaves outputs unchanged on failure.',
        'Starting at order zero always describes one complete frame. Each iteration asks whether doubling preserves both start alignment and containment in the remaining interval.',
        'end - first is safe after validating their order. The maximum-order bound keeps every shift representable.',
        'Insert the returned block into its order’s free list, set first = next_out, and repeat. Reserve metadata and subtract holes before calling this helper.'
      ]),
      trace('Decompose PFNs [3,29) with maximum order 4', ['Current first', 'Selected order and size', 'Block', 'Why a larger block fails'], [['3','order 0, one frame','[3,4)','PFN 3 is not divisible by 2.'],['4','order 2, four frames','[4,8)','PFN 4 is not divisible by 8.'],['8','order 3, eight frames','[8,16)','PFN 8 is not divisible by 16.'],['16','order 3, eight frames','[16,24)','A 16-frame block would end at 32, beyond 29.'],['24','order 2, four frames','[24,28)','Eight frames would end at 32.'],['28','order 0, one frame','[28,29)','Only one frame remains.']]),
      p('The six sizes sum to 26, exactly end minus start. Their intervals touch without overlapping. Every block start is aligned to its own size. These three properties are useful initialization assertions: complete coverage, disjointness, and alignment. A fourth assertion checks that each block remains within one zone and one normalized usable run.',
        'A reserved hole changes the decomposition. Removing PFNs [11,13) leaves runs [3,11) and [13,29). Decompose them independently. The left run yields starts/orders (3,0), (4,2), (8,1), (10,0). The right run yields (13,0), (14,1), (16,3), (24,2), (28,0). No order-3 block may cover [8,16), because that interval contains the reserved hole.',
        'The largest-at-the-front rule is greedy, but it does not sacrifice a valid larger block at the same starting point: any larger choice would violate alignment, capacity, or the maximum order. Subsequent boundaries become increasingly aligned until the interval’s tail forces smaller blocks. The simple helper checks at most maximum_order candidate doublings per emitted block. A count-trailing-zero/count-leading-zero implementation can reduce constants once zero inputs and word widths are handled deliberately.',
        'Coalescing later still requires same-order free buddies and zone compatibility. Initial list membership is an ownership statement. Do not insert the same run twice because overlapping firmware descriptors mention it twice; canonicalize the map first. Keep allocation-order metadata separate from the order used to partition an initial free run, since a split can change the latter before any caller receives memory.'),
      exercise('Partition a second run', 'Decompose PFNs [6,23) with maximum order 3.', ['List every start/order pair.', 'Verify complete coverage numerically.', 'Decide whether starts 8 and 16 can become one order-4 block under this allocator configuration.'], ['The pairs are (6,1), (8,3), (16,2), (20,1), (22,0). Their intervals are [6,8), [8,16), [16,20), [20,22), [22,23).', 'The sizes are 2 + 8 + 4 + 2 + 1 = 17, matching 23 - 6.', 'They cannot. The represented blocks have different sizes, the total run ends at 23, and maximum order 3 forbids order 4 even if a larger aligned free region later exists.'], ['Five emitted blocks cover exactly 17 frames.', 'Every start is divisible by its block size.'])
    ], [ref('Linux physical memory documentation', 'https://docs.kernel.org/mm/physical_memory.html', 'Zones and page allocation'), ref('OSDev companion: page-frame allocation', 'https://wiki.osdev.org/Page_Frame_Allocation', 'Buddy allocation overview; initialization here is an original bounded algorithm')])
  ],
  'virtual-memory': [],
  'kernel-heap': [],
  'elf-loader': []
};

memoryFurtherHandbook['virtual-memory'].push(
  topic('vm-hashed-inverted-reverse-maps', 'walk', 'Compare hashed translation, inverted tables, and reverse mappings', [
    'A hierarchical page table answers a forward question: given an address-space context and virtual page, which frame and permissions apply? Other data structures can answer the same question with different memory costs. Start by writing the complete lookup key, because a virtual page number alone cannot distinguish two processes using the same address.',
    'The examples here are software data-structure models. The course’s legacy x86 MMU still requires its architecturally defined directory and table formats. A hash table can support kernel bookkeeping, but placing its address in CR3 would not teach the hardware a new lookup algorithm.'
  ], [
    table('Separate three related structures', ['Structure', 'Primary key', 'Stored relationship'], [['Hashed forward table','Address-space identifier plus VPN','A chain or probe sequence leads to PFN and permissions.'],['Inverted frame table','Physical frame number','One base entry per frame records its identity and ownership; a forward-lookup index is additionally needed.'],['Reverse mapping index','Physical frame or backing object page','Enumerates every virtual mapping that must be updated or revoked.']]),
    trace('Eight buckets; h(context, VPN) = (3 × context + VPN) mod 8', ['Entry or request','Hash arithmetic','Bucket 1 chain or outcome'], [['Insert context 2, VPN 11 → PFN 41','(6 + 11) mod 8 = 1','(2,11,41)'],['Append context 5, VPN 2 → PFN 9','(15 + 2) mod 8 = 1','(2,11,41) → (5,2,9)'],['Append context 2, VPN 19 → PFN 62','(6 + 19) mod 8 = 1','(2,11,41) → (5,2,9) → (2,19,62)'],['Lookup context 2, VPN 19','Compare both context and VPN at each node','Third node matches; offset 0x2A yields physical 0x3E02A.'],['Lookup context 5, VPN 10','(15 + 10) mod 8 = 1','All three keys differ; consult valid-region/backing metadata.']]),
      p('A hash collision means that different keys share a bucket. It does not authorize using the first entry’s frame. With separate chaining, expected lookup work is proportional to one plus the load factor M/B when hashing distributes M mappings across B buckets reasonably. Worst-case lookup still visits M entries. An attacker-controlled or pathological address pattern can concentrate collisions, so capacity planning and a suitable hash function matter.',
        'An inverted table scales its base storage with physical frames. For 1 GiB of RAM and 4 KiB frames, there are 262144 frame entries. At an assumed 16 bytes per entry, the base table occupies 4 MiB. That calculation omits hash buckets, collision links, synchronization, and alias records. Compare complete structures before claiming a memory saving against sparse multilevel page tables.',
        'Shared memory exposes a limitation of a single owner field. Suppose context 2 VPN 11 and context 8 VPN 7 both map PFN 41. One inverted record cannot hold two independent virtual names unless it points to additional mapping records or another representation of the sharing relation. Each mapping can also have different permissions: one read-only and one writable, subject to the backing-object policy.',
        'Reverse mappings help reclaim and migration find those aliases. To revoke PFN 41, the kernel must identify both address spaces, update their relevant entries, complete translation invalidations, and retain the frame until access through every alias is retired. Scanning every page table in every process would be expensive. An index maintained when mappings are created and removed turns that global search into work proportional to the frame’s actual aliases.',
        'Forward and reverse metadata must change atomically under a documented lock and lifetime protocol. Publishing a PTE before registering its reverse map can make an eviction scanner miss a live alias. Removing the reverse record before the PTE becomes unreachable creates the same gap. Context identifiers also need lifetime rules so a recycled identifier cannot match stale translation metadata from an earlier process.'),
      exercise('Add and remove a shared alias', 'Add context 8 VPN 7 → PFN 41 to the example. Later, context 2 removes VPN 11.', ['Compute the new forward hash bucket.', 'Describe the reverse records for PFN 41 before and after removal.', 'Determine whether the physical frame may be freed after the first unmap.'], ['(3 × 8 + 7) mod 8 = 31 mod 8 = 7.', 'Initially PFN 41 has aliases (2,11) and (8,7). After completing removal of the first mapping, the remaining alias is (8,7).', 'The frame remains owned because the second mapping still references it. Its final release also requires any other references and stale translations to be retired.'], ['Alias bucket = 7.', 'One surviving mapping prevents frame reuse.'])
  ], [ostep('Paging: smaller tables', 'vm-smalltables', 'Section 20.4: inverted page tables'), osc, ref('Philipp Oppermann: paging introduction', 'https://os.phil-opp.com/paging-introduction/', 'Hardware translation hierarchy and page-table structure')]),
  topic('vm-conditional-access-time', 'tlb', 'Calculate access time with conditional misses and fault service', [
    'An effective-access-time equation is a probability model. Name mutually exclusive paths, give each path a complete cost, and ensure their probabilities add to one. Many incorrect calculations count a successful memory access twice or apply a conditional miss rate to all accesses.',
    'Use an intentionally simplified machine: a TLB lookup takes 2 ns, each serialized memory access takes 70 ns, and an uncached four-level walk reads four entries before accessing the requested data. Ignore parallel lookup, speculative execution, and data-cache hits so each arithmetic step remains visible.'
  ], [
    table('Complete costs for resident-page accesses', ['Path', 'Cost derivation', 'Complete cost'], [['TLB hit','2 + 70','72 ns'],['TLB miss, all four levels uncached','2 + 4 × 70 + 70','352 ns'],['TLB miss, top two levels supplied by walk cache','2 + 2 × 70 + 70','212 ns']]),
    p('Assume 60% of TLB misses use the two cached upper levels and 40% need all four memory reads. The conditional miss cost is 0.60 × 212 + 0.40 × 352 = 268 ns. If the TLB hit probability is h = 0.97, the resident-access mean is h × 72 + (1 - h) × 268 = 77.88 ns. The 60% value applies only within the 3% miss population.',
      'Equivalently, classify all accesses as 97% TLB hits, 1.8% shortened walks, and 1.2% full walks. Their probabilities sum to 100%. This expansion is a useful audit because it reveals whether a branch probability was accidentally used at the wrong level.'),
    trace('Expand the probability tree before summing', ['Event', 'Unconditional probability', 'Contribution to mean'], [['TLB hit','0.97','0.97 × 72 = 69.84 ns'],['Miss with upper levels cached','0.03 × 0.60 = 0.018','0.018 × 212 = 3.816 ns'],['Miss with full walk','0.03 × 0.40 = 0.012','0.012 × 352 = 4.224 ns'],['Total','1.000','77.88 ns']]),
    p('Now add page faults using a second explicit model. Let p be the unconditional probability of a major fault, q the unconditional probability of a minor fault, and T the mean of accesses that fault neither way. If Fmajor and Fminor are complete service times including the eventual successful access, E = (1 - p - q)T + qFminor + pFmajor. If a quoted fault latency excludes replay, add the replay cost to that path first.',
      'For T = 77.88 ns, q = 0.0001, Fminor = 5000 ns, p = 0.000001, and Fmajor = 3000000 ns, the mean is 81.37213412 ns. The major-fault contribution alone is 3 ns even though only one access in a million takes that branch. Units matter: 3 ms equals 3000000 ns, so writing 3 into the nanosecond equation would understate the contribution by a factor of one million.',
      'A target can be inverted into a budget. With q = 0 and a 90 ns mean-time ceiling, p must be at most (90 - 77.88)/(3000000 - 77.88), approximately 0.0000040401. That is about four major faults per million accesses under these assumptions. This target depends on the declared model and requires measurements before application to a real processor.',
      'A mean also hides the waiting-time distribution. A 3 ms major fault can dominate an individual request’s tail latency even while the average increases only slightly. Measure fault classes, TLB behavior, queueing, and request percentiles when applying the model to a workload. Changing page size may change hit probability, walk depth, physical contiguity demands, and internal waste together.'),
    exercise('Find a hit-ratio requirement', 'Keep the resident hit cost 72 ns and conditional miss cost 268 ns. Require resident mean access time at most 80 ns, with no page faults.', ['Solve for the minimum h.', 'Calculate the mean when h = 0.95.', 'Explain why a 99% TLB hit rate says nothing by itself about the major-fault probability.'], ['72h + 268(1 - h) <= 80 gives 268 - 196h <= 80, so h >= 188/196 = 47/49, approximately 95.9184%.', 'At h = 0.95, the mean is 68.4 + 13.4 = 81.8 ns, which exceeds the target.', 'TLB statistics concern translation caching. Major faults concern missing resident backing and need a separately defined population and counter.'], ['Minimum h = 47/49.', '95% gives 81.8 ns.'])
  ], [osc, ostep('Translation lookaside buffers', 'vm-tlbs', 'TLB lookup and miss behavior'), ostep('Beyond physical memory: mechanisms', 'vm-beyondphys', 'Page-fault service and replacement mechanism')]),
  topic('vm-clean-reserves-reclaim-pacing', 'faults', 'Maintain a clean-page reserve before an urgent allocation', [
    'A replacement policy can identify a cold page while the allocator still waits for that page’s contents to become safely recoverable. Background cleaning moves eligible dirty pages toward a state where reclaim can release them promptly. A reserve of clean reclaimable pages gives urgent allocations room to proceed while slower writeback is in flight.',
    'Track at least free frames, clean eligible candidates, dirty eligible candidates, pages under writeback, and pinned or otherwise ineligible pages. Their counts answer different questions. A page being written to storage remains owned throughout that operation and contributes no immediately reusable frame.'
  ], [
    table('Candidate state at the instant of a scan', ['State', 'Action available now', 'Condition before reuse'], [['Clean, cold, unpinned, recoverable','Begin revoking mappings and references','Complete revocation and lifetime retirement.'],['Dirty, cold, eligible','Schedule cleaning within the I/O budget','Successful backing update, then revalidate coldness and revocability.'],['Writeback in flight','Wait or choose another candidate','Completion and any later writes must be accounted for.'],['Recently referenced','Give another chance or age according to policy','A later scan can reconsider its activity.'],['Pinned or required by an active operation','Exclude from the available reserve','The owner must explicitly release its pin or dependency.']]),
    p('Use two watermarks to avoid repeatedly starting and stopping the cleaner at one boundary. In a simple model, start cleaning when the clean reserve falls below 8 pages, and continue until it reaches 20 pages. Count the reserve using pages that are actually eligible for the intended allocation class. Twenty remote or device-inaccessible frames cannot satisfy a strict local DMA request.',
      'Assume a 5 ms observation interval, initial clean reserve 18 pages, no initially free frames, and demand consuming 6 clean pages per interval. The cleaner can complete 10 eligible dirty pages per interval after a one-interval delay. Each completion creates clean candidates; it does not itself revoke their mappings. For this arithmetic exercise, assume revocation is immediate, candidates remain cold, and none are redirtied.'),
    trace('Sample after demand; completions occur at the beginning of each interval', ['Interval', 'Starting reserve including completions', 'After demand consumes 6', 'Cleaner decision'], [['1','18','12','Idle: reserve is at least 8.'],['2','12','6','Start: submit 10 pages for the next interval.'],['3','6 + 10 = 16','10','Continue: submit another 10.'],['4','10 + 10 = 20','14','Continue: submit another 10.'],['5','14 + 10 = 24','18','Continue: submit another 10.'],['6','18 + 10 = 28','22','Stop: high watermark 20 has been reached.'],['7','22','16','Idle.'],['8','16','10','Idle.'],['9','10','4','Start another cleaning cycle.']]),
    p('The hysteresis band absorbs ordinary fluctuations. During cleaning, supply exceeds demand by four pages per interval in this example. If writeback completed only four pages while demand consumed six, the reserve would shrink by two per active interval. Raising the high watermark would not repair that sustained deficit; the kernel needs lower demand, more reclaimable capacity, faster backing service, or an explicit allocation-failure policy.',
      'Set a writeback budget as well as a reserve target. Submitting every dirty page at once can saturate storage queues and delay interactive reads. A controller can limit pages in flight, bytes per interval, or time spent scanning, while reserving resources needed to complete already-submitted I/O. The I/O path must be able to allocate its own required metadata without recursively exhausting the reserve it is meant to replenish.',
      'Actual eligibility must be rechecked after I/O. A page may become hot, gain a pin, acquire another mapping, or be dirtied again. The filesystem writeback state machine handles whether the completed write covers the current contents. Reclaim additionally proves that all current users can be detached. A successful disk completion alone never licenses immediate frame reuse.',
      'Collect separate counters for pages scanned, pages found cold, pages skipped because pinned, writes submitted, writes completed, and frames actually freed. A high scan rate with few eligible candidates indicates a different bottleneck from a large writeback queue. These observations let you diagnose whether policy, ownership constraints, or storage throughput limits progress.'),
    exercise('Stress the cleaner’s throughput', 'The reserve is 14 pages. Demand consumes 7 per interval, and an already-running cleaner completes 5 pages at the beginning of each interval.', ['Calculate reserves after four intervals.', 'State whether the queue can recover while those rates remain fixed.', 'Explain how redirtying two of each five completed pages changes the effective supply.'], ['The sequence is 12, 10, 8, 6 because each interval adds five and consumes seven.', 'It cannot recover: demand exceeds supply by two pages per interval.', 'Only three completed pages remain clean candidates, so the reserve decreases by four per interval under the simplified eligibility assumptions.'], ['Four-interval reserve = 6.', 'Redirtying reduces effective clean supply to 3 pages per interval.'])
  ], [ostep('Beyond physical memory: mechanisms', 'vm-beyondphys', 'When replacement happens: low and high watermarks'), ref('Linux memory-management APIs', 'https://docs.kernel.org/core-api/mm-api.html', 'Writeback, dirty state, and page lifetime'), ref('Linux physical memory documentation', 'https://docs.kernel.org/mm/physical_memory.html', 'Reclaim and allocation watermarks')])
);

memoryFurtherHandbook['kernel-heap'].push(
  topic('heap-checkpointed-bump-arenas', 'implementation', 'Use checkpointed arenas when objects share a lifetime', [
    'Some kernel work produces many temporary objects that all become dead together: parsing a boot configuration, building a provisional executable-load plan, or collecting one diagnostic snapshot. A bounded arena can allocate those objects by advancing a cursor and reclaim the whole group at a checkpoint rollback.',
    'The important design choice is the lifetime boundary. A general free-list allocator supports independently ending object lifetimes. A checkpointed arena makes allocation simpler by requiring every object after a checkpoint to become dead before that checkpoint is restored. Escaping pointers violate the contract even when the cursor arithmetic is correct.'
  ], [
    code('An original checked offset allocator for one bounded arena', 'c', '#include <stdint.h>\n#include <stdbool.h>\nstruct arena { uint32_t capacity, next; };\n\nbool arena_take(struct arena *a, uint32_t bytes,\n                uint32_t alignment, uint32_t *offset) {\n    if (!bytes || !alignment || (alignment & (alignment - 1u)))\n        return false;\n    if (a->next > a->capacity) return false;\n    uint32_t remainder = a->next & (alignment - 1u);\n    uint32_t padding = remainder ? alignment - remainder : 0;\n    if (padding > a->capacity - a->next) return false;\n    uint32_t start = a->next + padding;\n    if (bytes > a->capacity - start) return false;\n    a->next = start + bytes;\n    *offset = start;\n    return true;\n}\n\nbool arena_rewind(struct arena *a, uint32_t checkpoint) {\n    if (a->next > a->capacity || checkpoint > a->next) return false;\n    a->next = checkpoint;\n    return true;\n}', [
      'a and offset must be valid writable objects. The backing arena base must satisfy every requested alignment; otherwise an aligned offset does not establish an aligned absolute address.',
      'The allocator checks a nonzero power-of-two alignment and computes padding from the current remainder. It never evaluates an overflowing next + alignment - 1 expression.',
      'Subtraction checks prove each addition remains within capacity. Failure leaves both the cursor and output unchanged.',
      'A checkpoint is a previously saved next value from this same arena. arena_rewind checks numerical bounds only; the caller must prove checkpoint provenance and that all later objects are dead.',
      'This is a single-threaded offset model with no payload storage, destructors, or automatic clearing. Allocation and numerical rewind are O(1).'
    ]),
    trace('A 256-byte arena with a 64-byte-aligned backing base', ['Operation','Returned offset','New cursor and explanation'], [['Allocate 13 bytes aligned to 8','0','13'],['Save checkpoint','No allocation','checkpoint = 13'],['Allocate 20 bytes aligned to 16','16','36; three bytes of padding'],['Allocate 64 bytes aligned to 64','64','128; twenty-eight bytes of padding'],['Destroy both temporary objects and rewind','No allocation','13; the first 13-byte object remains live'],['Allocate 8 bytes aligned to 8','16','24; the previous temporary area is reusable']]),
    p('Rollback often belongs to a larger transaction. Save a checkpoint before constructing provisional objects, retain external resources in a cleanup list, and on failure release those resources before rewinding their bookkeeping storage. If the cleanup list itself lives after the checkpoint, rewinding first erases the records needed to close files, drop frame references, or detach mappings.',
      'A successful transaction may need to promote selected objects into longer-lived storage. Copy or transfer them according to an explicit ownership plan before rewinding the temporary arena. Retaining an interior pointer into the arena is unsafe because the next transaction can reuse the same bytes for a different object. A generation number in a debug handle can help detect this mistake, but raw C pointers do not carry that generation.',
      'Internal padding is the main allocation overhead in this model. The example’s two temporary objects request 84 bytes, advance the cursor from 13 to 128, and consume 31 padding bytes. A short-lived phase can tolerate this bounded waste in exchange for simple cleanup. Mixing one long-lived object among temporary allocations can prevent the intended rewind and retain the entire suffix.',
      'Choose the allocator by measured workload and ownership needs. A bump arena fits group lifetimes; fixed-size caches fit repeated objects with independent lifetimes; a coalescing free list fits varied sizes and varied lifetimes. Required worst-case latency, interrupt context, synchronization, alignment, and observability can matter more than average allocation throughput.'),
    exercise('Reject an oversized aligned request', 'The cursor is 225 in a 256-byte arena. Request 16 bytes aligned to 64.', ['Compute the padding and aligned start.', 'Explain why allocation fails and what state remains unchanged.', 'State why rewinding to an arbitrary number such as 17 is unsafe even if the arithmetic helper accepts it.'], ['225 mod 64 is 33, so padding is 31 and aligned start is 256.', 'No payload bytes remain at start 256; the 16-byte request fails. The cursor stays 225 and the output retains its prior value.', '17 may split a live object or be unrelated to any checkpoint from this arena. Numeric containment does not prove the lifetime and provenance contract.'], ['Padding = 31; aligned start = 256.', 'Failure preserves allocator state.'])
  ], [ref('Philipp Oppermann: allocator designs', 'https://os.phil-opp.com/allocator-designs/', 'Bump allocator and lifetime limitations'), ostep('Free-space management', 'vm-freespace', 'Allocation mechanisms and workload-dependent policy')])
);

memoryFurtherHandbook['elf-loader'].push(
  topic('elf32-relocation-arithmetic', 'format', 'Relocate ELF32 references using symbol, addend, and place', [
    'Mapping an executable’s bytes establishes its memory image, but some object formats still contain addresses or displacements that depend on final placement. A relocation record tells a linker or loader which field to update and which arithmetic to apply. This extension begins only after the simpler fixed-address loader is working.',
    'Use the i386 ELF32 ABI for these examples. Distinguish a link-time relocatable object from a fixed-address executable and a position-independent shared object. A bounded teaching loader may continue rejecting dynamic images until symbol lookup, relocation validation, and runtime startup contracts are implemented together.'
  ], [
    table('Symbols used in the relocation calculation', ['Symbol','Meaning','Original example value'], [['S','Resolved runtime address of the referenced symbol','0x0804B120'],['A','Addend associated with this relocation','4, or -4 for the displayed branch displacement'],['P','Runtime address of the field being relocated','0x08049024'],['B','Chosen load bias of an object','0x20000000 in a separate placement example']]),
    p('An ELF32 Rel record contains r_offset and r_info. The low eight bits of r_info hold the relocation type, and the upper bits hold the symbol-table index under the ELF32 convention. For a REL relocation, the addend is already stored in the target field. A RELA record instead carries an explicit signed addend. Decode according to the record type before modifying any bytes; reading an addend after overwriting its field loses the original input.',
      'The place P is the address of the relocated field. For a PC-relative instruction displacement, it can differ from the instruction’s first byte and from the CPU’s eventual next-instruction address. The toolchain encodes the appropriate adjustment in the addend. Applying an extra guessed instruction-length correction can therefore offset the result twice.'),
    trace('Two i386 relocation formulas applied independently', ['Relocation','Calculation','Stored 32-bit result'], [['R_386_32, A = 4','S + A = 0x0804B120 + 4','0x0804B124; bytes 24 B1 04 08'],['R_386_PC32, A = -4','S + A - P = 0x0804B120 - 4 - 0x08049024','0x000020F8; bytes F8 20 00 00'],['Same PC32 references shifted by B = 0x20000000','(S + B) + A - (P + B)','Still 0x000020F8 because B cancels']]),
    code('Arithmetic helper after relocation validation', 'c', '#include <stdint.h>\n#include <stdbool.h>\n\nbool i386_relocation_word(uint32_t type, uint32_t symbol,\n                          uint32_t addend_bits, uint32_t place,\n                          uint32_t *word) {\n    if (type == 1u) { /* R_386_32 */\n        *word = symbol + addend_bits;\n        return true;\n    }\n    if (type == 2u) { /* R_386_PC32 */\n        *word = symbol + addend_bits - place;\n        return true;\n    }\n    return false;\n}', [
      'The helper operates on 32-bit words with defined unsigned modulo-2^32 arithmetic. Encode addend -4 as 0xFFFFFFFC. word must be valid writable storage.',
      'It supports only the two displayed relocation types and preserves output for other types. It does not parse a relocation table, resolve symbols, or write into an executable mapping.',
      'A real loader validates the target four-byte extent, symbol index, supported type, source addend, and permission policy before calling arithmetic or storing the result.',
      'Serialize the returned word in little-endian order or use a validated architecture-appropriate write. An unaligned file pointer cast is an unnecessary assumption.'
    ]),
    p('Build a relocation plan before publishing an executable address space. For every record, prove that its record bytes are within the relocation table, its target field is inside a permitted loaded region, and its referenced symbol is resolvable under the chosen ABI. Reject unknown types explicitly. A symbol-table index that fits in the file can still refer to an undefined symbol requiring a dependency that the teaching loader does not support.',
      'Relocation writes can conflict with final read-only permissions. Perform initialization through controlled kernel mappings while the new image is private, then establish the final access policy. A relocation into executable code also raises sharing and write/execute-policy questions. These questions belong in the loader contract before support for arbitrary dynamic binaries is claimed.',
      'Applying the same REL relocation twice is usually wrong because the second pass may read the already-relocated result as a fresh addend. Record completion or rebuild from pristine input after failure. Rollback must discard the partially prepared private image or restore original words; retrying blindly over mutated bytes can silently corrupt every relocated address.'),
    exercise('Calculate a negative PC-relative result', 'S = 0x08048010, P = 0x08049004, and the REL target initially contains the addend -4.', ['Calculate S + A - P as a signed mathematical difference.', 'Encode the result as a 32-bit word and little-endian bytes.', 'Explain why shifting both S and P by the same load bias preserves the displacement.'], ['The difference is -0xFF8, or -4088.', 'Modulo 2^32, the result is 0xFFFFF008; bytes are 08 F0 FF FF.', 'The added bias appears once positively and once negatively, so it cancels from S + B + A - (P + B).'], ['Result word = 0xFFFFF008.', 'Little-endian bytes = 08 F0 FF FF.'])
  ], [ref('System V ELF ABI: relocation records', 'https://refspecs.linuxfoundation.org/elf/gabi4+/ch4.reloc.html', 'REL, RELA, r_offset, and r_info'), ref('System V ELF specification', 'https://refspecs.linuxfoundation.org/elf/elf.pdf', 'Book II, Intel Architecture relocation types: R_386_32 and R_386_PC32')])
);
